# SOME DESCRIPTIVE TITLE.
# Copyright (C) Plone community and other individual contributors
# This file is distributed under the same license as the Plone Developer Documentation package.
# 
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: plone-doc\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-02-08 13:29\n"
"PO-Revision-Date: 2014-02-08 12:46+0000\n"
"Last-Translator: Giacomo <giacomo.spettoli@gmail.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: en\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

# 242dcc22464f42b79cdcfad1a6862b47
#: ../../source/troubleshooting/basic.rst:3
msgid "Basic troubleshooting"
msgstr "Basic troubleshooting"

# c20da110846f4f199c5cfe840983bfb8
#: ../../source/troubleshooting/basic.rst:7
msgid ""
"Here is some info for basic Plone troubleshooting, especially with add-on "
"modules-"
msgstr "Here is some info for basic Plone troubleshooting, especially with add-on modules-"

# 4c016d14801848908b81386b08d3155f
#: ../../source/troubleshooting/basic.rst:12
msgid "Start Plone as foreground / debug mode"
msgstr "Start Plone as foreground / debug mode"

# 66338e8124624123bd74f29dc8a489db
#: ../../source/troubleshooting/basic.rst:14
msgid ""
"Plone runs on the top of Zope application service. Zope is a Python process "
"and will appear as \"python .....\" in your task manager process list."
msgstr "Plone runs on the top of Zope application service. Zope is a Python process and will appear as \"python .....\" in your task manager process list."

# 48fe204e8d6c4063a288602f1bacad1a
#: ../../source/troubleshooting/basic.rst:17
msgid ""
"Zope will report any problems with code when it is launched in foreground "
"mode (attached to a terminal)."
msgstr "Zope will report any problems with code when it is launched in foreground mode (attached to a terminal)."

# b6ca21c4994c4180ae534b3c7be49ce0
#: ../../source/troubleshooting/basic.rst:19
msgid "Basic command-line knowledge is needed in order to proceed"
msgstr "Basic command-line knowledge is needed in order to proceed"

# ef5e820e474a48659e9daf87f07c6732
#: ../../source/troubleshooting/basic.rst:21
msgid "First stop Zope if it's running as a background process"
msgstr "First stop Zope if it's running as a background process"

# 431f971066a84d9abab25546046b0275
#: ../../source/troubleshooting/basic.rst:23
msgid ""
"On Windows: use Plone Control Panel or Windows Control Panel Services "
"section to shutdown Plone first"
msgstr "On Windows: use Plone Control Panel or Windows Control Panel Services section to shutdown Plone first"

# 74bd874851b3427297f7b95ce36de74f
#: ../../source/troubleshooting/basic.rst:25
msgid ""
"On Linux: use /etc/init.d/plone stop or related command to shutdown Plone"
msgstr "On Linux: use /etc/init.d/plone stop or related command to shutdown Plone"

# 5aef42b292e84cba8ee0403443cce251
#: ../../source/troubleshooting/basic.rst:27
msgid "Use the command"
msgstr "Use the command"

# 54cd61cf1bb84a12941053feaeb1c4b8
#: ../../source/troubleshooting/basic.rst:33
msgid ""
"or Windows command-line command (note that Plone location may depend on "
"where you installed it)"
msgstr "or Windows command-line command (note that Plone location may depend on where you installed it)"

# f829570dfddb450786e5d7c8d778356f
#: ../../source/troubleshooting/basic.rst:40
msgid "to start Plone."
msgstr "to start Plone."

# 11d841a2ab124b568e6ede30e4fc2e84
#: ../../source/troubleshooting/basic.rst:42
msgid ""
"All errors will be printed into the terminal. The error is printed as Python"
" *traceback*. It is important to copy-paste all lines of this traceback, not"
" just the last line."
msgstr "All errors will be printed into the terminal. The error is printed as Python *traceback*. It is important to copy-paste all lines of this traceback, not just the last line."

# 4f001f121f6a417a9f77e68f20880210
#: ../../source/troubleshooting/basic.rst:46
msgid "If there is no start up error you will see the line"
msgstr "If there is no start up error you will see the line"

# 8e2e9e3ab1994daba01e0a079fcfecb8
#: ../../source/troubleshooting/basic.rst:49
msgid "No such file or directory: 'zope.conf'"
msgstr "No such file or directory: 'zope.conf'"

# 97a07c9c32b7469ea1468a247bbfbce2
# 4840be4921a44839a5e4166564e1d362
#: ../../source/troubleshooting/basic.rst:51
#: ../../source/troubleshooting/buildout.rst:127
msgid "Example:"
msgstr "Example:"

# b443d309aba44b43b9949da2b2bc1d12
#: ../../source/troubleshooting/basic.rst:53
msgid ""
"sudo /Applications/Plone/zinstance/bin/plonectl start instance: Error: error"
" opening file /Applications/Plone/zinstance/parts/instance/etc/zope.conf: "
"[Errno 2] No such file or directory: "
"'/Applications/Plone/zinstance/parts/instance/etc/zope.conf'"
msgstr "sudo /Applications/Plone/zinstance/bin/plonectl start instance: Error: error opening file /Applications/Plone/zinstance/parts/instance/etc/zope.conf: [Errno 2] No such file or directory: '/Applications/Plone/zinstance/parts/instance/etc/zope.conf'"

# 1875aac12f464ea5bb3da9405e4ab051
#: ../../source/troubleshooting/basic.rst:56
msgid ""
"This means that running ``bin/buildout`` script did not complete "
"successfully. Re-run buildout and see what's wrong."
msgstr "This means that running ``bin/buildout`` script did not complete successfully. Re-run buildout and see what's wrong."

# b05ca61c65a3443db6436641a9e6da0f
#: ../../source/troubleshooting/basic.rst:60
msgid "Dropping into pdb"
msgstr "Dropping into pdb"

# bbe9c3b45a6147c7ad97ab4b691cab8f
#: ../../source/troubleshooting/basic.rst:62
msgid ""
"If you need to inspect start-up errors in Python's :doc:`debugger "
"</testing_and_debugging/pdb>`."
msgstr "If you need to inspect start-up errors in Python's :doc:`debugger </testing_and_debugging/pdb>`."

# cc355ef653a0401999871cad4680f1d7
#: ../../source/troubleshooting/basic.rst:64
msgid ""
"Activate Python configuration associated with your ``bin/instance`` script::"
msgstr "Activate Python configuration associated with your ``bin/instance`` script::"

# da8c51c8494e407db904f80a10dc6266
#: ../../source/troubleshooting/basic.rst:68
msgid "Start Plone pdb enabled::"
msgstr "Start Plone pdb enabled::"

# 05993699cfc74f948e95b88da6cf605b
#: ../../source/troubleshooting/basic.rst:73
msgid "Check if Plone is up and responds to requests"
msgstr "Check if Plone is up and responds to requests"

# d66a7c9e330f4615adc261d60aa0c556
#: ../../source/troubleshooting/basic.rst:75
msgid "Enter to the computer running Plone (SSH in on UNIX)."
msgstr "Enter to the computer running Plone (SSH in on UNIX)."

# f4d8d28e185d4d329d2eb727e7edd48a
#: ../../source/troubleshooting/basic.rst:77
msgid ""
"Use ``telnet`` command to connect Plone port and see if you get valid HTTP "
"response from Plone"
msgstr "Use ``telnet`` command to connect Plone port and see if you get valid HTTP response from Plone"

# 2bce3dd8edad46db83957d077307ae63
#: ../../source/troubleshooting/basic.rst:83
msgid "Then do a human HTTP user agent simulation by typing::"
msgstr "Then do a human HTTP user agent simulation by typing::"

# b72dd3852ec64bfd880f48f3bbec0c9d
#: ../../source/troubleshooting/basic.rst:87
msgid "Plone response looks like this::"
msgstr "Plone response looks like this::"

# fd3912bc0d484dc89fb0d4c59ef45c9f
#: ../../source/troubleshooting/basic.rst:108
msgid ""
"If you get the answer from Plone (based on HTTP response headers) then Plone"
" is running and you have problem elsewhere in your firewall/server/ front-"
"end web server configuration."
msgstr "If you get the answer from Plone (based on HTTP response headers) then Plone is running and you have problem elsewhere in your firewall/server/ front-end web server configuration."

# e0705cbfcff645eb968f27fe47e40e7e
#: ../../source/troubleshooting/basic.rst:112
msgid "Consult your operating system manual for fixing your problem."
msgstr "Consult your operating system manual for fixing your problem."

# 4577d7e3e5994f81954f4ab7f636f647
#: ../../source/troubleshooting/basic.rst:115
msgid "Cleaning up bad add-on uninstalls"
msgstr "Cleaning up bad add-on uninstalls"

# e3cf294fdc734b54a28aa5d9f2e37923
#: ../../source/troubleshooting/basic.rst:117
msgid ""
"Many low quality Plone add-ons do not uninstall cleanly. You need to remove "
"persistent objects from site database *after* add-on uninstall while *code "
"is still in buildout*."
msgstr "Many low quality Plone add-ons do not uninstall cleanly. You need to remove persistent objects from site database *after* add-on uninstall while *code is still in buildout*."

# c2f2919fe36248038fd2731213ab9b49
#: ../../source/troubleshooting/basic.rst:121
msgid "Otherwise your Plone site may not"
msgstr "Otherwise your Plone site may not"

# eba5345f628f4ee9a07518661fd7538a
#: ../../source/troubleshooting/basic.rst:123
msgid "Pack properly"
msgstr "Pack properly"

# 8e4a3012974140fc9b6005ef998c50cb
#: ../../source/troubleshooting/basic.rst:125
msgid "Start properly"
msgstr "Start properly"

# 87253b96bf84464888d9a760bd162c73
#: ../../source/troubleshooting/basic.rst:127
msgid "Migrate to new version"
msgstr "Migrate to new version"

# d39dcf780ff4417da67336c3a9f0bc83
# 75e58ea3addf4831951b7178cbcbd6bd
#: ../../source/troubleshooting/basic.rst:129
#: ../../source/troubleshooting/images.rst:110
msgid "For more information see"
msgstr "For more information see"

# f16cb35c4e9043c3a19fd2111d5ed9f0
# 95e08f418365409f8bb71ff3693f9eb6
# 3fe45eb5c8d6496f9dde5bfa21f62ed6
#: ../../source/troubleshooting/basic.rst:131
#: ../../source/troubleshooting/exceptions.rst:1401
#: ../../source/troubleshooting/exceptions.rst:1788
msgid ""
"http://plone.org/documentation/kb/manually-removing-local-persistent-"
"utilities/"
msgstr "http://plone.org/documentation/kb/manually-removing-local-persistent-utilities/"

# 940f30cdafd443c9a197f377935b1d15
#: ../../source/troubleshooting/basic.rst:134
msgid "Not able to log in"
msgstr "Not able to log in"

# 4638aa4e571a45a695cc4b435b394eb4
#: ../../source/troubleshooting/basic.rst:136
msgid ""
"It might happen that you start your instance with an empty database and you "
"are not able to log in even if you are absolutely sure about your password. "
"If you work on localhost throw away the localhost related cookies in your "
"browser and restart."
msgstr "It might happen that you start your instance with an empty database and you are not able to log in even if you are absolutely sure about your password. If you work on localhost throw away the localhost related cookies in your browser and restart."

# 770c1379492545cdbf7705377dfce3d5
#: ../../source/troubleshooting/basic.rst:140
msgid ""
"If you have lost the Zope Admin Password you can create an emergency user:"
msgstr "If you have lost the Zope Admin Password you can create an emergency user:"

# cc5eacfda7b3490489a589db2975080c
#: ../../source/troubleshooting/basic.rst:142
msgid "http://quintagroup.com/services/support/tutorials/zope-access"
msgstr "http://quintagroup.com/services/support/tutorials/zope-access"

# a4db257c77e441b39565966b2ff863b0
# afd87e899230421db6f579cb01d664a3
# 5c04742ee3e642fda04bcd07d7c057fb
# e5ae8e378c174bb288bd6e8fe8fadcc1
# 7fdb0cf564fa4f1fae277043df020cca
# f7153d408ccf48a18cff4c6b796c1772
# 6a216dd583c84bc2b65c00657aa73df6
# 474f1894f1c74b598fa8fe97f6d455af
# ab70a80252d0489d8748c06424db05de
#: ../../source/troubleshooting/basic.rst:146
#: ../../source/troubleshooting/buildout.rst:153
#: ../../source/troubleshooting/exceptions.rst:1095
#: ../../source/troubleshooting/exceptions.rst:1399
#: ../../source/troubleshooting/exceptions.rst:1827
#: ../../source/troubleshooting/exceptions.rst:1956
#: ../../source/troubleshooting/exceptions.rst:2040
#: ../../source/troubleshooting/transactions.rst:229
#: ../../source/troubleshooting/transactions.rst:250
msgid "More info"
msgstr "More info"

# 70c481c91c5a4148adcc52c520ee0b4c
#: ../../source/troubleshooting/basic.rst:148
msgid ""
":doc:`common exceptions which you might encounter when starting Zope "
"</troubleshooting/exceptions>`"
msgstr ":doc:`common exceptions which you might encounter when starting Zope </troubleshooting/exceptions>`"

# 7e657bde399746c69474ae819fa23ded
#: ../../source/troubleshooting/basic.rst:150
msgid ""
"`Plone community support guidelines for asking help "
"<http://plone.org/help>`_"
msgstr "`Plone community support guidelines for asking help <http://plone.org/help>`_"

# b4c30448b1ac4cedb9fcdac29c1cfb2a
#: ../../source/troubleshooting/buildout.rst:3
msgid "Buildout troubleshooting"
msgstr "Buildout troubleshooting"

# be4f2b5e00914a46a4ac3723aa844631
#: ../../source/troubleshooting/buildout.rst:7
msgid ""
"How to solve problems related to running buildout and some common exceptions"
" you might encounter when running buildout for Plone."
msgstr "How to solve problems related to running buildout and some common exceptions you might encounter when running buildout for Plone."

# cc327626930342ebbbed7d0a55954eec
# 4d38ea4d64fd44c2a3106c7f3b1d12a4
# 6a92ba0f548041c3a502c8f6e17edccc
#: ../../source/troubleshooting/buildout.rst:13
#: ../../source/troubleshooting/exceptions.rst:12
#: ../../source/troubleshooting/transactions.rst:12
msgid "Introduction"
msgstr "Introduction"

# 4a5ab592c61448c29301b4b732871793
#: ../../source/troubleshooting/buildout.rst:15
msgid "This document tells how to resolve buildout problems."
msgstr "This document tells how to resolve buildout problems."

# c082684f768445a98f088c6d26cf97f8
#: ../../source/troubleshooting/buildout.rst:18
msgid "Network errors and timeouts"
msgstr "Network errors and timeouts"

# bc10d7da05e342e19cc8648b25bfec23
#: ../../source/troubleshooting/buildout.rst:20
msgid "The usual reason for download error or timeout is that either"
msgstr "The usual reason for download error or timeout is that either"

# 1c1deffd82784ca98acbe0afa72d8db6
#: ../../source/troubleshooting/buildout.rst:22
msgid "``pypi.python.org`` server is down, or"
msgstr "``pypi.python.org`` server is down, or"

# a9cb9067572546c89cfae226f688c39a
#: ../../source/troubleshooting/buildout.rst:23
msgid "one of ``plone.org`` servers is down, or"
msgstr "one of ``plone.org`` servers is down, or"

# fa3cb7f9da8d49279a19f5e08c8131fe
#: ../../source/troubleshooting/buildout.rst:24
msgid "other Python package source server is down."
msgstr "other Python package source server is down."

# 029e339877d340dfbe20e914e4f0dd12
#: ../../source/troubleshooting/buildout.rst:26
msgid ""
"Here are instructions how to deal with community servers down situations"
msgstr "Here are instructions how to deal with community servers down situations"

# 84ede8ce36ce4f8aa68bdbf53ba64290
#: ../../source/troubleshooting/buildout.rst:28
msgid "http://jacobian.org/writing/when-pypi-goes-down/"
msgstr "http://jacobian.org/writing/when-pypi-goes-down/"

# e9ec149c0d114da89affad6eec42db55
#: ../../source/troubleshooting/buildout.rst:30
msgid "Mirrors"
msgstr "Mirrors"

# 29b71e1290dd415f8aaa97ae7c7f8fed
#: ../../source/troubleshooting/buildout.rst:32
msgid "http://pypi.appspot.com/"
msgstr "http://pypi.appspot.com/"

# 3adeceac8638418bb1554bed3cf97ef1
#: ../../source/troubleshooting/buildout.rst:35
msgid "Individual package failing outside PyPI"
msgstr "Individual package failing outside PyPI"

# 864ff93ab43e4fc99d1c6f777486d00d
#: ../../source/troubleshooting/buildout.rst:37
msgid ""
"To figure out which file buildout tries to download, usually the only way is"
" to use ``buildout -D`` pdb debug mode and step up in stack frames to see "
"what is going on."
msgstr "To figure out which file buildout tries to download, usually the only way is to use ``buildout -D`` pdb debug mode and step up in stack frames to see what is going on."

# a0cf85cd11fe471db3fbf277384be089
#: ../../source/troubleshooting/buildout.rst:42
msgid "parts/instance/etc/zope.conf: [Errno 2] No such file or directory"
msgstr "parts/instance/etc/zope.conf: [Errno 2] No such file or directory"

# 93ed80d5279b4c7a8142633b7672683b
#: ../../source/troubleshooting/buildout.rst:45
msgid ""
"You see this error when trying to start Plone. This means that buildout did "
"not complete correctly and did not generate configuration files."
msgstr "You see this error when trying to start Plone. This means that buildout did not complete correctly and did not generate configuration files."

# e100fdfce9354091905afdefab4a2ba1
#: ../../source/troubleshooting/buildout.rst:48
msgid ""
"Rerun buildout and fix errors in ``buildout.cfg`` based on buildout command "
"output."
msgstr "Rerun buildout and fix errors in ``buildout.cfg`` based on buildout command output."

# 138b3f38d47640c6bc309ee9ca9c537c
#: ../../source/troubleshooting/buildout.rst:51
msgid "Buildout and SyntaxErrors"
msgstr "Buildout and SyntaxErrors"

# 88c101e2e9ab4acbaac0cbe11bdf208e
#: ../../source/troubleshooting/buildout.rst:53
msgid "You may see ``SyntaxError`` exceptions when running buildout::"
msgstr "You may see ``SyntaxError`` exceptions when running buildout::"

# fb6ee2b8ffe44e8a8d21fe1beae5d053
#: ../../source/troubleshooting/buildout.rst:57
msgid "They are harmless."
msgstr "They are harmless."

# ed1bda38c2a9406a96cb555c5a6905c9
#: ../../source/troubleshooting/buildout.rst:59
msgid ""
"The reason: Buildout uses a Python tool called ``setuptools`` internally to "
"install the packages.  setuptools scans all ``.py`` files inside the Python "
"package and assumes they are Python modules.  However, Plone has something "
"called :doc:`RestrictedPython </security/sandboxing>`. RestrictedPython "
"allows untrusted users to execute Python code in Plone (Python Scripts in "
"the :term:`ZMI`).  RestrictedPython scripts use slightly modified Python "
"syntax compared to plain Python modules."
msgstr "The reason: Buildout uses a Python tool called ``setuptools`` internally to install the packages.  setuptools scans all ``.py`` files inside the Python package and assumes they are Python modules.  However, Plone has something called :doc:`RestrictedPython </security/sandboxing>`. RestrictedPython allows untrusted users to execute Python code in Plone (Python Scripts in the :term:`ZMI`).  RestrictedPython scripts use slightly modified Python syntax compared to plain Python modules."

# c68b9b02cd24486aa5cc04f91b09b004
#: ../../source/troubleshooting/buildout.rst:67
msgid ""
"setuptools does not know which files are normal ``.py`` and which files are "
"RestrictedPython and tries to interpret them all using standard Python "
"syntax rules. Then it fails. However, setuptools only tries to scan files "
"(for what?) but still installs them correctly. No harm done."
msgstr "setuptools does not know which files are normal ``.py`` and which files are RestrictedPython and tries to interpret them all using standard Python syntax rules. Then it fails. However, setuptools only tries to scan files (for what?) but still installs them correctly. No harm done."

# b7cf19903bc54e7c9c7c381c49ce2ea6
#: ../../source/troubleshooting/buildout.rst:74
msgid "Version conflicts"
msgstr "Version conflicts"

# 661bea32503c483e84a91540fdd3e5d8
#: ../../source/troubleshooting/buildout.rst:76
msgid ""
"Buildout gives you an error if there is a dependency shared by two "
"components, and one of the components wants to have a different version of "
"this dependency."
msgstr "Buildout gives you an error if there is a dependency shared by two components, and one of the components wants to have a different version of this dependency."

# e6790dc0c10a4e93a3d5a4c2aa15816f
# 67a51a6120a34ac287df629103c4f54e
# 9627fdaad3f54534b1168b73d67d389b
# 1199e40f35df444ca749b261a8250bbf
# 5bf28df3911a4ac0b46c2f0382702cc4
# 8985154a074e42959b754c24e03a4c12
# e0283ac9de174ea79c155024814c1fa1
# 05c282c25ebe4cea98ea400933035f3c
# 7e388ddcfa9b49e782e83db0dd94ec90
# 968e8cfa688548718c67a4ea41041da1
# 4b7cbb93ffe74dfd8590ebfaaad5972e
# 95830fc7fd17478ea99e40b343016181
# fc5df8177ce843e68a7c5c1cb04ed0ac
# 05bf6d1541d24cffb499126d88bb8c30
# 757e838af7a5466cb58dc6f834f198e1
# 3f26a8ce50704b4f88fb245df94780c5
# 45b761e490044fa89fb2f599ecd73e8c
# 1f0e4e90facb47468a5af1bec5bf056a
# 0cd7fd1a49394041af1a7c2f24094e3c
# 78760e4908b84e059cb1295675095fb6
# 6d4b83c0f5f744fc86d5474142d80f2f
#: ../../source/troubleshooting/buildout.rst:79
#: ../../source/troubleshooting/buildout.rst:149
#: ../../source/troubleshooting/buildout.rst:263
#: ../../source/troubleshooting/buildout.rst:546
#: ../../source/troubleshooting/buildout.rst:574
#: ../../source/troubleshooting/buildout.rst:622
#: ../../source/troubleshooting/exceptions.rst:193
#: ../../source/troubleshooting/exceptions.rst:227
#: ../../source/troubleshooting/exceptions.rst:250
#: ../../source/troubleshooting/exceptions.rst:286
#: ../../source/troubleshooting/exceptions.rst:574
#: ../../source/troubleshooting/exceptions.rst:857
#: ../../source/troubleshooting/exceptions.rst:1410
#: ../../source/troubleshooting/exceptions.rst:1497
#: ../../source/troubleshooting/exceptions.rst:1952
#: ../../source/troubleshooting/exceptions.rst:2069
#: ../../source/troubleshooting/exceptions.rst:2087
#: ../../source/troubleshooting/exceptions.rst:2111
#: ../../source/troubleshooting/images.rst:117
#: ../../source/troubleshooting/unicode.rst:39
#: ../../source/troubleshooting/unicode.rst:107
msgid "Example::"
msgstr "Example::"

# c4bdc899bae7466790464e90ddf44a30
#: ../../source/troubleshooting/buildout.rst:88
msgid "If your buildout is fetching strange versions:"
msgstr "If your buildout is fetching strange versions:"

# ee96df1c202349498e7cdca2251aacc4
#: ../../source/troubleshooting/buildout.rst:90
msgid "try running buildout in verbose mode: ``bin/buildout -vvv``"
msgstr "try running buildout in verbose mode: ``bin/buildout -vvv``"

# df04bfe9641345089ed3aaf32b1ba832
#: ../../source/troubleshooting/buildout.rst:91
msgid "Use dumppickedversions (below)"
msgstr "Use dumppickedversions (below)"

# 4c46d076c288441da717503d12207d0e
#: ../../source/troubleshooting/buildout.rst:92
msgid ""
"Manually pin down version in the ``[versions]`` section of your buildout."
msgstr "Manually pin down version in the ``[versions]`` section of your buildout."

# 39558f0b978a4c7a8033e82a3d93e192
#: ../../source/troubleshooting/buildout.rst:94
msgid "Further reading:"
msgstr "Further reading:"

# 19e4c45de6b945b7b2089cd171b22dcc
#: ../../source/troubleshooting/buildout.rst:96
msgid "http://maurits.vanrees.org/weblog/archive/2010/08/fake-version-pinning"
msgstr "http://maurits.vanrees.org/weblog/archive/2010/08/fake-version-pinning"

# 4e69ddf4db4a402c914206f4c53398ac
#: ../../source/troubleshooting/buildout.rst:98
msgid ""
"http://www.uwosh.edu/ploneprojects/documentation/how-tos/how-to-use-"
"buildout-to-pin-product-versions"
msgstr "http://www.uwosh.edu/ploneprojects/documentation/how-tos/how-to-use-buildout-to-pin-product-versions"

# d0205b77a4fa4bc0ae95cf6bcf3a1ff2
#: ../../source/troubleshooting/buildout.rst:101
msgid "Dump picked versions"
msgstr "Dump picked versions"

# a69879e48918407bb7bf2a4d63f32cf0
#: ../../source/troubleshooting/buildout.rst:103
msgid ""
"This buildout extension will automatically dump picked Python egg versions "
"to a file."
msgstr "This buildout extension will automatically dump picked Python egg versions to a file."

# 34f59f6e5cb647588d5ec0bbf9ea948b
#: ../../source/troubleshooting/buildout.rst:106
msgid "Add to your ``buildout.cfg``:"
msgstr "Add to your ``buildout.cfg``:"

# 1c2667151f6945208660a845d1e6bb8f
# af5e38d4955f4ea2a3150a14878542df
#: ../../source/troubleshooting/buildout.rst:114
#: ../../source/troubleshooting/exceptions.rst:1203
msgid "More information"
msgstr "More information"

# 14426fff9ad74244a62aeb54829a847f
#: ../../source/troubleshooting/buildout.rst:116
msgid ""
"`dumppickedversions "
"<http://pypi.python.org/pypi/buildout.dumppickedversions>`_"
msgstr "`dumppickedversions <http://pypi.python.org/pypi/buildout.dumppickedversions>`_"

# b4c8b0f711244ac7a28ca3759fc5e45b
#: ../../source/troubleshooting/buildout.rst:119
msgid "Good-py service"
msgstr "Good-py service"

# c015e20c85bd48d6a820c8f4a2a518ae
#: ../../source/troubleshooting/buildout.rst:121
msgid ""
"Good-py contains some good known versions sets. These are most convenient to"
" use if you are using complex configuration of add-ons that you are not "
"familiar with."
msgstr "Good-py contains some good known versions sets. These are most convenient to use if you are using complex configuration of add-ons that you are not familiar with."

# 695be9466117455995578db2bf0bf29b
#: ../../source/troubleshooting/buildout.rst:125
msgid "Some good-py configurations take a Plone version as a paremeter."
msgstr "Some good-py configurations take a Plone version as a paremeter."

# ce18ad0b14494757952aebc835049bb7
#: ../../source/troubleshooting/buildout.rst:137
msgid "Or:"
msgstr "Or:"

# 5640cd95d1724a4886a460f16ab61cfa
#: ../../source/troubleshooting/buildout.rst:147
msgid "Extracting version numbers from instance script"
msgstr "Extracting version numbers from instance script"

# 6859cecd1646434b9414920cadbc0402
#: ../../source/troubleshooting/buildout.rst:155
msgid ""
"http://davidjb.com/blog/2011/06/extracting-a-buildout-versions-cfg-from-a"
"-zope-instance-script/"
msgstr "http://davidjb.com/blog/2011/06/extracting-a-buildout-versions-cfg-from-a-zope-instance-script/"

# 97e0c775092c42c4ab017d17f0ada9d9
#: ../../source/troubleshooting/buildout.rst:158
msgid "Plone 3.1"
msgstr "Plone 3.1"

# aa75d903c946490f93eaa9f5ea711d32
#: ../../source/troubleshooting/buildout.rst:160
msgid ""
"Plone 3.1 and earlier are not eggified. Below are links how to keep Plone "
"3.1 and earlier buildouts running."
msgstr "Plone 3.1 and earlier are not eggified. Below are links how to keep Plone 3.1 and earlier buildouts running."

# b742e3f448af4d7dae26a6d4d0137ebe
#: ../../source/troubleshooting/buildout.rst:163
msgid "See:"
msgstr "See:"

# 7869259c69f24744b890041ea4a76177
#: ../../source/troubleshooting/buildout.rst:165
msgid "http://maurits.vanrees.org/weblog/archive/2010/04/nonewplone"
msgstr "http://maurits.vanrees.org/weblog/archive/2010/04/nonewplone"

# 7577bc77f6a4413799418173f66d3597
#: ../../source/troubleshooting/buildout.rst:167
msgid "http://plone.org/documentation/kb/repair-a-plone-3.1-buildout"
msgstr "http://plone.org/documentation/kb/repair-a-plone-3.1-buildout"

# 77af316b1b784cb88289c29fd83bbed5
#: ../../source/troubleshooting/buildout.rst:171
msgid "Common pindowns"
msgstr "Common pindowns"

# 024c366204af4993be5500214cfa361f
#: ../../source/troubleshooting/buildout.rst:173
msgid "Here is a latest pindown example from 2010/02:"
msgstr "Here is a latest pindown example from 2010/02:"

# fa4ec79d456a43daa5dd9dc26214e49c
#: ../../source/troubleshooting/buildout.rst:194
msgid "Getting distribution for ``distribute``"
msgstr "Getting distribution for ``distribute``"

# e9dced69c2d14d20b65619b687341561
#: ../../source/troubleshooting/buildout.rst:196
msgid "You try to run buildout, but it is stuck in a loop::"
msgstr "You try to run buildout, but it is stuck in a loop::"

# 9ef70ddd7bae4fb9a0d2beeed9960f1b
#: ../../source/troubleshooting/buildout.rst:205
msgid ""
"Your system-wide Distribute version is older than the latest release. "
"Buildout tries to update it, but since system wide site-packages version "
"overrides anything buildout can do, it is stuck in a loop."
msgstr "Your system-wide Distribute version is older than the latest release. Buildout tries to update it, but since system wide site-packages version overrides anything buildout can do, it is stuck in a loop."

# 7d80557bb2764664bb1036dabc2a41a5
#: ../../source/troubleshooting/buildout.rst:209
msgid "Fix: update Distribute in system-wide Python::"
msgstr "Fix: update Distribute in system-wide Python::"

# d88836c7c7ae48b094e4dcb80feb2b6f
#: ../../source/troubleshooting/buildout.rst:235
msgid "UnknownExtra: zope.i18n 0.0 has no such extra feature 'zcml'"
msgstr "UnknownExtra: zope.i18n 0.0 has no such extra feature 'zcml'"

# 6646a96eac3940d0815d66de81948b51
#: ../../source/troubleshooting/buildout.rst:237
msgid "You get the following traceback when running buildout::"
msgstr "You get the following traceback when running buildout::"

# c4ae72bbdbed45abb8890dc5791b6a5c
#: ../../source/troubleshooting/buildout.rst:251
msgid ""
"You might be using an add-on meant for Plone 4 with Plone 3. Check if "
"``setup.py`` contains *Zope2* as a dependency. If it does, then you need to "
"use earlier version of the add-on for your Plone 3 site."
msgstr "You might be using an add-on meant for Plone 4 with Plone 3. Check if ``setup.py`` contains *Zope2* as a dependency. If it does, then you need to use earlier version of the add-on for your Plone 3 site."

# e9205ad1e7ab4258824a71c1c088ef7c
# 33472a710e184999b721f439a4947981
#: ../../source/troubleshooting/buildout.rst:255
#: ../../source/troubleshooting/exceptions.rst:693
msgid "More info:"
msgstr "More info:"

# 635b9900ea30497d8f9e4fe89b6d5b3f
#: ../../source/troubleshooting/buildout.rst:257
msgid ""
"http://groups.google.com/group/singing-"
"dancing/browse_thread/thread/331cdfe78cf371ed"
msgstr "http://groups.google.com/group/singing-dancing/browse_thread/thread/331cdfe78cf371ed"

# 3d08ff7339894af2bdc298cb5cc4ffd6
#: ../../source/troubleshooting/buildout.rst:261
msgid "We already have: zope.interface 4.0.3"
msgstr "We already have: zope.interface 4.0.3"

# 180800936d344d888a71db4ced70dc00
#: ../../source/troubleshooting/buildout.rst:276
msgid ""
"Your system Python or virtualenv'd Python already has ``zope.interface`` "
"library installed. A lot of Python software uses this library. However, the "
"system version is wrong and cannot be overridden."
msgstr "Your system Python or virtualenv'd Python already has ``zope.interface`` library installed. A lot of Python software uses this library. However, the system version is wrong and cannot be overridden."

# f5469ebe22d64250acb1cde78ba8658c
#: ../../source/troubleshooting/buildout.rst:279
msgid "Solutions."
msgstr "Solutions."

# 8768298b32824e2c8d00a4d3b99d1117
#: ../../source/troubleshooting/buildout.rst:281
msgid ""
"For virtualenv: ``rm -rf ~/code/plone-venv/lib/python2.7/site-"
"packages/zope.interface-4.0.3-py2.7-macosx-10.8-x86_64.egg``"
msgstr "For virtualenv: ``rm -rf ~/code/plone-venv/lib/python2.7/site-packages/zope.interface-4.0.3-py2.7-macosx-10.8-x86_64.egg``"

# c90ddfc4791943d881d894a5e00025d4
#: ../../source/troubleshooting/buildout.rst:283
msgid ""
"For system Python: You need to create a virtualenv'd Python and to use it to"
" drive buildout, so that there is no conflict with ``zope.interface`` "
"versions."
msgstr "For system Python: You need to create a virtualenv'd Python and to use it to drive buildout, so that there is no conflict with ``zope.interface`` versions."

# d6092d53eee445c799a33e9f8ecc2c19
#: ../../source/troubleshooting/buildout.rst:287
msgid "We already have: zope.location 3.4.0"
msgstr "We already have: zope.location 3.4.0"

# e4b9179350434f31bbdb08ceae99d403
#: ../../source/troubleshooting/buildout.rst:289
msgid "When running buildout, Plone 3.3.5::"
msgstr "When running buildout, Plone 3.3.5::"

# d62cd759c8a442f6a0ba90cd448d5239
# 0412bfd7b20d497595972fb8423b879b
#: ../../source/troubleshooting/buildout.rst:305
#: ../../source/troubleshooting/buildout.rst:591
msgid "Solution:"
msgstr "Solution:"

# 40ba36d4ee1d46b6934a70f535d207c6
#: ../../source/troubleshooting/buildout.rst:315
msgid "ImportError: No module named lxml"
msgstr "ImportError: No module named lxml"

# 9da584fe0ee4400ea15f51b5d29ab4d5
#: ../../source/troubleshooting/buildout.rst:317
msgid ""
"``lxml`` as a PyPi package dependency fails even though it is clearly "
"installed."
msgstr "``lxml`` as a PyPi package dependency fails even though it is clearly installed."

# aec0ad61b96940ffb917b4e3639c7ef2
# 7254a03511104ea8a011d1bf8d9ec384
#: ../../source/troubleshooting/buildout.rst:320
#: ../../source/troubleshooting/buildout.rst:603
msgid "Example traceback when running buildout::"
msgstr "Example traceback when running buildout::"

# 6d47b99a06664a87b64cd4ed257e3cea
#: ../../source/troubleshooting/buildout.rst:339
msgid ""
"Solution: ensure lxml compilation happens before openxmllib is being "
"compiled."
msgstr "Solution: ensure lxml compilation happens before openxmllib is being compiled."

# 3de22ca9687f487380cad75a90815ac4
#: ../../source/troubleshooting/buildout.rst:342
msgid ""
"For instance, if you are installing something like ``Products.OpenXml``, you"
" will have likely included this egg under your Plone ``[instance]`` section "
"of your buildout.  You should consider using something like "
"``collective.recipe.staticlxml`` to build lxml and to do this *before* this "
"egg's installation is invoked. Like so in your ``buildout.cfg``:"
msgstr "For instance, if you are installing something like ``Products.OpenXml``, you will have likely included this egg under your Plone ``[instance]`` section of your buildout.  You should consider using something like ``collective.recipe.staticlxml`` to build lxml and to do this *before* this egg's installation is invoked. Like so in your ``buildout.cfg``:"

# 1b3b5890ca454242a8708576bdd5f701
#: ../../source/troubleshooting/buildout.rst:361
msgid "More information:"
msgstr "More information:"

# e08754f922e7494e952d0d0758f2d439
#: ../../source/troubleshooting/buildout.rst:363
msgid "http://www.niteoweb.com/blog/order-of-parts-when-compiling-lxml"
msgstr "http://www.niteoweb.com/blog/order-of-parts-when-compiling-lxml"

# 1b7153f27c824678b46ec03793f100d4
#: ../../source/troubleshooting/buildout.rst:365
msgid ""
"http://plone.293351.n2.nabble.com/lxml-installs-but-Products-OpenXml-"
"openxmllib-can-t-see-it-tp5565184p5565184.html"
msgstr "http://plone.293351.n2.nabble.com/lxml-installs-but-Products-OpenXml-openxmllib-can-t-see-it-tp5565184p5565184.html"

# 1ee9285d780e4a4c9b8c118ef98a0980
#: ../../source/troubleshooting/buildout.rst:368
msgid "UnknownExtra: zope.i18n 3.4.0 has no such extra feature 'zcml'"
msgstr "UnknownExtra: zope.i18n 3.4.0 has no such extra feature 'zcml'"

# e947f66110e440858cc316ae3adb5769
# 0cac2a209af14c6fa33c15fdc71ede85
# b629b817e28644169bc1291a469ee677
# acabc9013aad49a5ab283748873b9ded
# 0c83ea9cf43543698b2c4e7a243e93d9
# b74e8ecff7784970930069976281c814
# 011095c1ca8c47ddae9b19943ef3211d
# aee5a8f1446042cfba7b2520930d7e89
#: ../../source/troubleshooting/buildout.rst:370
#: ../../source/troubleshooting/exceptions.rst:1172
#: ../../source/troubleshooting/exceptions.rst:1292
#: ../../source/troubleshooting/exceptions.rst:1339
#: ../../source/troubleshooting/exceptions.rst:1529
#: ../../source/troubleshooting/exceptions.rst:1616
#: ../../source/troubleshooting/exceptions.rst:1766
#: ../../source/troubleshooting/exceptions.rst:1865
msgid "Traceback::"
msgstr "Traceback::"

# 7357a37085c44eefb18591350ec565b6
#: ../../source/troubleshooting/buildout.rst:395
msgid ""
"Solution: Check that you have the correct Dexteriry or XDV pindowns / Known "
"Good Set of versions or whether you are using a Plone 4 extension in Plone "
"3.  For example: ``plone.reload`` 2.0 will raise this with a Plone 3.3 "
"buildout, while ``plone.reload`` 1.5 will work with Plone 3.3."
msgstr "Solution: Check that you have the correct Dexteriry or XDV pindowns / Known Good Set of versions or whether you are using a Plone 4 extension in Plone 3.  For example: ``plone.reload`` 2.0 will raise this with a Plone 3.3 buildout, while ``plone.reload`` 1.5 will work with Plone 3.3."

# 758b28a8f515402e994fb93d5ee1ec6b
#: ../../source/troubleshooting/buildout.rst:400
msgid ""
"See Also: `UnknownExtra: zope.i18n 0.0 has no such extra feature 'zcml'`_"
msgstr "See Also: `UnknownExtra: zope.i18n 0.0 has no such extra feature 'zcml'`_"

# 89ae9f33709d4714acbced6ddacfa6a1
#: ../../source/troubleshooting/buildout.rst:404
msgid "Can't run ``bootstrap.py`` - VersionConflict for ``zc.buildout``"
msgstr "Can't run ``bootstrap.py`` - VersionConflict for ``zc.buildout``"

# 332250fc53b44835ac5db7e7e1c8b759
#: ../../source/troubleshooting/buildout.rst:406
msgid "Traceback when running ``python bootstrap.py``::"
msgstr "Traceback when running ``python bootstrap.py``::"

# 0b76d6e39db44d9caf1a306f283da2fa
#: ../../source/troubleshooting/buildout.rst:424
msgid "Solution: update the ``zc.buildout`` installed in your system Python:"
msgstr "Solution: update the ``zc.buildout`` installed in your system Python:"

# c78993b6c8c345719de0e7978509d0ba
#: ../../source/troubleshooting/buildout.rst:431
msgid ""
"An error occurred when trying to install lxml - error: Setup script exited "
"with error: command 'gcc' failed with exit status 1"
msgstr "An error occurred when trying to install lxml - error: Setup script exited with error: command 'gcc' failed with exit status 1"

# 290e41907a604431a896c21f4d1f41b6
#: ../../source/troubleshooting/buildout.rst:433
msgid "Traceback when running buildout::"
msgstr "Traceback when running buildout::"

# 6f99ddbcfda1432da21b38a20ed651a5
#: ../../source/troubleshooting/buildout.rst:446
msgid "Solution: install the ``libxml`` and ``libxslt`` development headers."
msgstr "Solution: install the ``libxml`` and ``libxslt`` development headers."

# f9e2b4107d0e40e1b07ea72622548c61
#: ../../source/troubleshooting/buildout.rst:448
msgid "On Ubuntu/Debian you could do this as follows:"
msgstr "On Ubuntu/Debian you could do this as follows:"

# b1c0c96cf6c34f27b109c66d5091b879
#: ../../source/troubleshooting/buildout.rst:456
msgid "VersionConflict: distribute 0.6.19"
msgstr "VersionConflict: distribute 0.6.19"

# 63c8a1f1b81d447e96ead077bfb71c57
#: ../../source/troubleshooting/buildout.rst:458
msgid "When running buildout you see something like this::"
msgstr "When running buildout you see something like this::"

# a0c442a1018e449d9b7b0a998bd19e06
#: ../../source/troubleshooting/buildout.rst:466
msgid ""
"Buildout uses the system-wide Distribute installation (``python-distribute``"
" or similar package, depends on your OS).  To fix this, you need to update "
"system-wide distribution."
msgstr "Buildout uses the system-wide Distribute installation (``python-distribute`` or similar package, depends on your OS).  To fix this, you need to update system-wide distribution."

# 97794371543a4be488117df9b25cd07d
#: ../../source/troubleshooting/buildout.rst:470
msgid ""
"It is preferred to do your Python + buildout installation in a "
":term:`virtualenv`, in order not to break your OS"
msgstr "It is preferred to do your Python + buildout installation in a :term:`virtualenv`, in order not to break your OS"

# b24bc0f517f84dcab9b7c8b46afb5833
#: ../../source/troubleshooting/buildout.rst:473
msgid ""
"Update Distribute (Plone universal installer, using supplied "
"``easy_install`` script):"
msgstr "Update Distribute (Plone universal installer, using supplied ``easy_install`` script):"

# 7c945e7483184f35b1bf7e4f9d338df1
#: ../../source/troubleshooting/buildout.rst:480
msgid "Update Distribute (OSX/Ubuntu/Linux):"
msgstr "Update Distribute (OSX/Ubuntu/Linux):"

# f7b05c3c00da4aa0aef2d02863b4627b
#: ../../source/troubleshooting/buildout.rst:488
msgid "argparse 1.2.1"
msgstr "argparse 1.2.1"

# f42fa07a45a54f958433f0b5e654ee74
#: ../../source/troubleshooting/buildout.rst:490
msgid "If you get::"
msgstr "If you get::"

# 87a535cc84f2401b8576e3062e22b255
#: ../../source/troubleshooting/buildout.rst:498
msgid "Rerun ``bootstrap.py`` with the correct Python interpreter."
msgstr "Rerun ``bootstrap.py`` with the correct Python interpreter."

# 586253948b864651a1b3c12ad0e522c8
#: ../../source/troubleshooting/buildout.rst:502
msgid "``Error: Picked: <some.package> = <some.version>``"
msgstr "``Error: Picked: <some.package> = <some.version>``"

# db58eac5fea745c589320f6aa60d4ffa
#: ../../source/troubleshooting/buildout.rst:504
msgid "If you get something like this::"
msgstr "If you get something like this::"

# d401f093657147548336e1fd0f0e7965
#: ../../source/troubleshooting/buildout.rst:520
msgid ""
"This means that your buildout has \"allow picked versions\" set to false. "
"You need to pin the version for the picked version (or turn on \"allow "
"picked versions\")."
msgstr "This means that your buildout has \"allow picked versions\" set to false. You need to pin the version for the picked version (or turn on \"allow picked versions\")."

# 237d29e94562416d80780de6998a0742
#: ../../source/troubleshooting/buildout.rst:525
msgid "Buildout error: ``Not a recognized archive type``"
msgstr "Buildout error: ``Not a recognized archive type``"

# 2c93350a43714c22808b39857b706814
#: ../../source/troubleshooting/buildout.rst:527
msgid "If you run across an error like this when running buildout::"
msgstr "If you run across an error like this when running buildout::"

# d125303dd49f46b2a117ee0a1d711a86
#: ../../source/troubleshooting/buildout.rst:534
msgid ""
"the error is likely stemming from an incorrect download of this egg. Check "
"the given file to ensure that the file is correct (for instance, it is a "
"non-zero length file or verifying the content using something like "
"``md5sum``) before delving deep into your Python install's workings. This "
"error makes it look as if your Python install doesn't have support for this "
"type of archive, but in fact it can be caused by a corrupt download."
msgstr "the error is likely stemming from an incorrect download of this egg. Check the given file to ensure that the file is correct (for instance, it is a non-zero length file or verifying the content using something like ``md5sum``) before delving deep into your Python install's workings. This error makes it look as if your Python install doesn't have support for this type of archive, but in fact it can be caused by a corrupt download."

# be0e46fdbfa845d5a3c30bea3da7e63c
#: ../../source/troubleshooting/buildout.rst:542
msgid ""
"VersionConflict: zope.browserpage 3.9.0 requires 'zope.publisher>=3.8'."
msgstr "VersionConflict: zope.browserpage 3.9.0 requires 'zope.publisher>=3.8'."

# 928b8c53e68e4e9aa860615fa4828ea4
#: ../../source/troubleshooting/buildout.rst:544
msgid "Plone 3.3.x package pindown problems."
msgstr "Plone 3.3.x package pindown problems."

# e4f4f26171054d7892f81c9d7ac1fb74
#: ../../source/troubleshooting/buildout.rst:552
msgid "Plone 3.x problem. Pin plone.uuid to 1.0.0."
msgstr "Plone 3.x problem. Pin plone.uuid to 1.0.0."

# 35c27430616b4c6c83d3f49a3d1fef39
#: ../../source/troubleshooting/buildout.rst:554
msgid "For Plone 3.3.x You need to pindown::"
msgstr "For Plone 3.3.x You need to pindown::"

# 273769c2defc4ab9943b3608a386c70a
#: ../../source/troubleshooting/buildout.rst:569
msgid ""
"Distribute / setuptools tries to mess with system Python and Permission "
"denied"
msgstr "Distribute / setuptools tries to mess with system Python and Permission denied"

# 94d731399fe845c1b53fe832160ff7fa
#: ../../source/troubleshooting/buildout.rst:571
msgid ""
"When running ``bootsrap.py`` your buildout files because it tries to write "
"to system-wide Python installation."
msgstr "When running ``bootsrap.py`` your buildout files because it tries to write to system-wide Python installation."

# d26b173b975640578a55a49b1ab8e862
#: ../../source/troubleshooting/buildout.rst:593
msgid ""
"`This bug has been fixed in Distiribute 0.6.27 "
"<http://pypi.python.org/pypi/distribute/0.6.27#id2>`_ - make sure your "
"system-wide Python uses this version or above::"
msgstr "`This bug has been fixed in Distiribute 0.6.27 <http://pypi.python.org/pypi/distribute/0.6.27#id2>`_ - make sure your system-wide Python uses this version or above::"

# 56e503ce65d740b5991e3339916b9049
#: ../../source/troubleshooting/buildout.rst:601
msgid ""
"UnboundLocalError: local variable 'clients' referenced before assignment"
msgstr "UnboundLocalError: local variable 'clients' referenced before assignment"

# d920465ba1bf420eb4c04d8528a3ea4d
#: ../../source/troubleshooting/buildout.rst:616
msgid ""
"Solution: Your buildout contains leftovers from the past. Remove ``clients``"
" variable in ``[unifiedinstaller]`` section."
msgstr "Solution: Your buildout contains leftovers from the past. Remove ``clients`` variable in ``[unifiedinstaller]`` section."

# d73d71ba97a24094936ca5f0c69d39c3
#: ../../source/troubleshooting/buildout.rst:620
msgid "Couldn't install: BTrees 4.0.5"
msgstr "Couldn't install: BTrees 4.0.5"

# cb5b251fb07d42e08d1194c399c54e0e
#: ../../source/troubleshooting/buildout.rst:644
msgid ""
"Plone 3.3.5 buildout ``fake-eggs`` is not working properly when you boostrap"
" the buildout in a new environment."
msgstr "Plone 3.3.5 buildout ``fake-eggs`` is not working properly when you boostrap the buildout in a new environment."

# fdedab1cff9f48f18b55feb0e2a083f1
#: ../../source/troubleshooting/buildout.rst:647
msgid ""
"Try install manually the core buildout part where you have ``fake-eggs`` "
"defined::"
msgstr "Try install manually the core buildout part where you have ``fake-eggs`` defined::"

# ac48b65e7bb34f619dc736753aa97a0e
#: ../../source/troubleshooting/buildout.rst:659
msgid "error: None"
msgstr "error: None"

# ccdde4a041bb405fb534be4050452d25
#: ../../source/troubleshooting/buildout.rst:661
msgid "This means .tar.gz is corrupted::"
msgstr "This means .tar.gz is corrupted::"

# f85532bef8044fdebfc689e86c6ff50f
#: ../../source/troubleshooting/buildout.rst:670
msgid ""
"Buildout download cache is corrupted. Run ``bin/buildout -vvv`` for more "
"info. Then do something like this::"
msgstr "Buildout download cache is corrupted. Run ``bin/buildout -vvv`` for more info. Then do something like this::"

# f0118999481940b6b9a0728d16540bfa
#: ../../source/troubleshooting/exceptions.rst:3
msgid "Exceptions and common tracebacks"
msgstr "Exceptions and common tracebacks"

# 03c88a261bea41e2b7eac12e4e0a9ee6
#: ../../source/troubleshooting/exceptions.rst:7
msgid ""
"Common Python exception traceback patterns you may encounter when working "
"with Plone."
msgstr "Common Python exception traceback patterns you may encounter when working with Plone."

# c6dad7934b744134be5f9c38dec99c27
#: ../../source/troubleshooting/exceptions.rst:14
msgid ""
"This document contains a list of common developer errors you might encounter"
" and possible solutions for them."
msgstr "This document contains a list of common developer errors you might encounter and possible solutions for them."

# 22cda1ca85944689a5cbd9f9ee225c28
#: ../../source/troubleshooting/exceptions.rst:16
msgid ""
"Please see :doc:`this tutorial </troubleshooting/basic>` for extracting "
"Python tracebacks from your Plone logs."
msgstr "Please see :doc:`this tutorial </troubleshooting/basic>` for extracting Python tracebacks from your Plone logs."

# 58eb684417994b50bf518a7af2cfcbe5
#: ../../source/troubleshooting/exceptions.rst:19
msgid ""
"AttributeError: 'str' object has no attribute 'other' (Mixed "
"zope.viewpagetemplate and Five.viewpagetemplate)"
msgstr "AttributeError: 'str' object has no attribute 'other' (Mixed zope.viewpagetemplate and Five.viewpagetemplate)"

# 3d8500974e6a49e2bec96f33dd6dfd89
# ceb4a257b56d4573b3b3fc0b354a0487
# a10e5068e2c147e98fbe2121ed5c343c
# b246850da0304dc9a03e58f82b5ee59d
# f99ad72e6c534017be4f4a82c98f2049
# 866a45665afa4eea93a63d58136001bb
# 1dc383521adc426ea5439232775c7325
# ec5f5e2c822d48ffa808f25590cd3145
# 1994bc4cadc14243bba27811bacaf9bb
# ca88a2675e2d4e4aa5fdde91d074baba
# 819bc66eeda94cdab0d500cce1aa9b7f
# 253e39550a424a37a50e8f0e33d7686a
#: ../../source/troubleshooting/exceptions.rst:21
#: ../../source/troubleshooting/exceptions.rst:121
#: ../../source/troubleshooting/exceptions.rst:344
#: ../../source/troubleshooting/exceptions.rst:796
#: ../../source/troubleshooting/exceptions.rst:820
#: ../../source/troubleshooting/exceptions.rst:931
#: ../../source/troubleshooting/exceptions.rst:955
#: ../../source/troubleshooting/exceptions.rst:1005
#: ../../source/troubleshooting/exceptions.rst:1127
#: ../../source/troubleshooting/exceptions.rst:1644
#: ../../source/troubleshooting/exceptions.rst:1714
#: ../../source/troubleshooting/exceptions.rst:2050
msgid "Example traceback::"
msgstr "Example traceback::"

# ee9ad682ce9b4125ac4ecdd0573b692d
#: ../../source/troubleshooting/exceptions.rst:50
msgid ""
"Five ViewPageTemplate class file is slightly different than Zope 3's normal "
"ViewPageTemplate file. In this case Five ViewPageTemplate was used, when "
"Zope 3's normal ViewPageTemplate was expected."
msgstr "Five ViewPageTemplate class file is slightly different than Zope 3's normal ViewPageTemplate file. In this case Five ViewPageTemplate was used, when Zope 3's normal ViewPageTemplate was expected."

# c964fbabd7a5474c91a384392cd4df7c
#: ../../source/troubleshooting/exceptions.rst:53
msgid ""
"Another reason is that acquisition chain is not properly set-up in your "
"custom views."
msgstr "Another reason is that acquisition chain is not properly set-up in your custom views."

# 66eaf1239cdb443dbc980c93674249c6
#: ../../source/troubleshooting/exceptions.rst:55
msgid "Difference::"
msgstr "Difference::"

# 223ceb47edd946d0b7ca8cf0358719c0
#: ../../source/troubleshooting/exceptions.rst:59
msgid "vs."
msgstr "vs."

# d69fdc79f51c45088a77e0cbc406a681
#: ../../source/troubleshooting/exceptions.rst:64
msgid "Iteration over non-sequence in _normalizeargs"
msgstr "Iteration over non-sequence in _normalizeargs"

# fccb2fd8c1d7460d8c52fc60fa594a9b
#: ../../source/troubleshooting/exceptions.rst:67
msgid "Case 1"
msgstr "Case 1"

# f795f38b67cd4e62bacade998bb6d5e5
#: ../../source/troubleshooting/exceptions.rst:69
msgid ""
"The following log trace will appear when you try to render the site, but you"
" can access ZMI normally::"
msgstr "The following log trace will appear when you try to render the site, but you can access ZMI normally::"

# 2d6b86f70d1d42f2a66ca05637b01ce5
#: ../../source/troubleshooting/exceptions.rst:112
msgid ""
"This usually means that you have copied Data.fs from another system, but you"
" do not have identical add-on product configuration installed."
msgstr "This usually means that you have copied Data.fs from another system, but you do not have identical add-on product configuration installed."

# d2b3a27ea5954268a23f1a8991ef38e8
#: ../../source/troubleshooting/exceptions.rst:116
msgid ""
"`For more info see this error reference on plone.org "
"<http://plone.org/documentation/error/typeerror-iteration-over-non-"
"sequence>`_."
msgstr "`For more info see this error reference on plone.org <http://plone.org/documentation/error/typeerror-iteration-over-non-sequence>`_."

# 5d191c4c93a9419084a8f5b07646454e
#: ../../source/troubleshooting/exceptions.rst:119
msgid "Case 2"
msgstr "Case 2"

# 64bbd5a6ec204b9aa72649cb6ee0cfe5
#: ../../source/troubleshooting/exceptions.rst:160
msgid ""
"Reason: You are trying to use Plone 4 (Zope 2.12) add-on on Plone 3 (Zope "
"2.10). Zope interface declarations have been changed."
msgstr "Reason: You are trying to use Plone 4 (Zope 2.12) add-on on Plone 3 (Zope 2.10). Zope interface declarations have been changed."

# 402f9d60f7ee4f1a93d8cd95c02ddaa4
#: ../../source/troubleshooting/exceptions.rst:162
msgid ""
"**Solution 1**: Pick the older version for the add-on which is known to work"
" with Plone 3. Make sure that you delete all \"too eggs\" from ``eggs/`` and"
" ``src/`` folders."
msgstr "**Solution 1**: Pick the older version for the add-on which is known to work with Plone 3. Make sure that you delete all \"too eggs\" from ``eggs/`` and ``src/`` folders."

# f1270e21014d4bfb8753b1d6e69c2814
#: ../../source/troubleshooting/exceptions.rst:165
msgid "**Solution 2**: Upgrade your site to Plone."
msgstr "**Solution 2**: Upgrade your site to Plone."

# 3ea078b2d7994d379866c889167f52a6
#: ../../source/troubleshooting/exceptions.rst:168
msgid "TraversalError with lots of tuples and lists (METAL problem)"
msgstr "TraversalError with lots of tuples and lists (METAL problem)"

# 78b6368d36bb484b927d41a2f0a472f5
#: ../../source/troubleshooting/exceptions.rst:170
msgid "Exception::"
msgstr "Exception::"

# f7c73d2fddfa4c42aeddc2385102401c
#: ../../source/troubleshooting/exceptions.rst:188
msgid ""
"Some template tries to call macro inside another template and the macro is "
"not defined in the target template."
msgstr "Some template tries to call macro inside another template and the macro is not defined in the target template."

# fc439cb0ecb4475d8dce719432a1c753
#: ../../source/troubleshooting/exceptions.rst:191
msgid "AttributeError in setRoles due to workflow state transition"
msgstr "AttributeError in setRoles due to workflow state transition"

# e5631a97c5904a539867b85d89f79004
#: ../../source/troubleshooting/exceptions.rst:215
msgid "Possible reasons"
msgstr "Possible reasons"

# e192d76a357e4e9e87a59ae151a836ce
#: ../../source/troubleshooting/exceptions.rst:217
msgid ""
"You are using AnnotationStorage but you forgot to declare "
"atapi.ATFieldProperty in your class body"
msgstr "You are using AnnotationStorage but you forgot to declare atapi.ATFieldProperty in your class body"

# 845b667f230148deba003bf962558bc6
#: ../../source/troubleshooting/exceptions.rst:219
msgid ""
"You are inhering schema in Archetypes, but you do not inherit the class "
"itself"
msgstr "You are inhering schema in Archetypes, but you do not inherit the class itself"

# 66a99c762f9c492aa4ad3901f0e54992
#: ../../source/troubleshooting/exceptions.rst:223
msgid "Add-on installer error: too many values to unpack"
msgstr "Add-on installer error: too many values to unpack"

# 18b620cbda774b87804fc47667ece772
#: ../../source/troubleshooting/exceptions.rst:225
msgid "An exception prevents running a quick installer."
msgstr "An exception prevents running a quick installer."

# 704b53da666f49c19a581f37fa9918a7
#: ../../source/troubleshooting/exceptions.rst:240
msgid "Reason:"
msgstr "Reason:"

# 261f3ea29d0b43699b181cc7fbb90add
#: ../../source/troubleshooting/exceptions.rst:242
msgid ""
"You have run Data.fs with zope.component 3.5.1, but later downgraded / moved"
" Data.fs. Pin zope.component to 3.5.1."
msgstr "You have run Data.fs with zope.component 3.5.1, but later downgraded / moved Data.fs. Pin zope.component to 3.5.1."

# 8ad57b79f5794a6693f8436bc8e3291c
#: ../../source/troubleshooting/exceptions.rst:245
msgid ""
"`See discussion <http://plone.org/support/forums/general#nabble-"
"td3257712%7Ca3257712>`_."
msgstr "`See discussion <http://plone.org/support/forums/general#nabble-td3257712%7Ca3257712>`_."

# c3bd9ea20f5448119dbe4937649a2ef7
#: ../../source/troubleshooting/exceptions.rst:248
msgid ""
"Add-on installer error: This object was originally created by a product that"
" is no longer installed"
msgstr "Add-on installer error: This object was originally created by a product that is no longer installed"

# f7136c8cb1074d0c8d5c1c55bb30e572
#: ../../source/troubleshooting/exceptions.rst:268
msgid ""
"Data.fs contains objects for which the code is not present. You have "
"probably moved Data.fs or edited buildout.cfg."
msgstr "Data.fs contains objects for which the code is not present. You have probably moved Data.fs or edited buildout.cfg."

# 5694c487b635475bbc18c4ec7cd3fc29
#: ../../source/troubleshooting/exceptions.rst:271
msgid ""
"Check that eggs and zcml contain all necessary products in buildout.cfg."
msgstr "Check that eggs and zcml contain all necessary products in buildout.cfg."

# d4a5c0fffe5d4c968bffac500b378e30
#: ../../source/troubleshooting/exceptions.rst:273
msgid "Discussion"
msgstr "Discussion"

# 6e06d0ae7b3c4f95a41d2b6eb78911e1
#: ../../source/troubleshooting/exceptions.rst:275
msgid "http://plone.org/support/forums/general#nabble-td3523234"
msgstr "http://plone.org/support/forums/general#nabble-td3523234"

# b097b2273443427884985e17afa156ef
#: ../../source/troubleshooting/exceptions.rst:277
msgid "http://article.gmane.org/gmane.comp.web.zope.plone.setup/3232"
msgstr "http://article.gmane.org/gmane.comp.web.zope.plone.setup/3232"

# 199243a14e7c42a3b92fa376c90534a9
#: ../../source/troubleshooting/exceptions.rst:281
msgid "z3c.form based form updateWidgets() raises ComponentLookupError"
msgstr "z3c.form based form updateWidgets() raises ComponentLookupError"

# ea197e2eeca845e6b0350fb60362939e
#: ../../source/troubleshooting/exceptions.rst:284
msgid "Case 1: z3c.form with Plone 3"
msgstr "Case 1: z3c.form with Plone 3"

# fe87d180117145b396dc1a756a60577f
#: ../../source/troubleshooting/exceptions.rst:306
msgid ""
"Reason: To use z3c.form based forms z3c.form.interfaces.IFormRequest must be"
" enabled for HTTP request object to make form layer adaptions work."
msgstr "Reason: To use z3c.form based forms z3c.form.interfaces.IFormRequest must be enabled for HTTP request object to make form layer adaptions work."

# 4646fada361043d989f315808900c91f
#: ../../source/troubleshooting/exceptions.rst:309
msgid "How to fix:"
msgstr "How to fix:"

# 9f441f41ac7d4caf86219bdb3e50d3f9
#: ../../source/troubleshooting/exceptions.rst:311
msgid ""
"Wrap your forms with plone.z3cform.layout.wrap_form() call as instructed in "
"plone.z3cform README"
msgstr "Wrap your forms with plone.z3cform.layout.wrap_form() call as instructed in plone.z3cform README"

# a7b02852e9df400cafe9f405126b0d50
#: ../../source/troubleshooting/exceptions.rst:313
msgid ""
"The same error occurs if plone.app.z3cform, plone.z3cform and z3c.form are "
"not properly included through ZCML. In order to be sure that those modules "
"are properly included, you can add the following lines into your "
"configure.zcml"
msgstr "The same error occurs if plone.app.z3cform, plone.z3cform and z3c.form are not properly included through ZCML. In order to be sure that those modules are properly included, you can add the following lines into your configure.zcml"

# ed3d8031b4d64d8d8b97affafbeb95de
#: ../../source/troubleshooting/exceptions.rst:322
msgid "...or you can use autoinclude feature for Plone 3.3+"
msgstr "...or you can use autoinclude feature for Plone 3.3+"

# d0ae2537410e402faa5d9a255bc6a2a5
#: ../../source/troubleshooting/exceptions.rst:324
msgid "in configure.zcml"
msgstr "in configure.zcml"

# 609958aeabcc4d9f8343e474411330ce
#: ../../source/troubleshooting/exceptions.rst:330
msgid "and then your add-on product setup.py file::"
msgstr "and then your add-on product setup.py file::"

# 8c061e0eb32043d98336d0181d8c2b2e
#: ../../source/troubleshooting/exceptions.rst:339
msgid ""
"Also remember to run Plone add-on installer for plone.app.z3cform (though it"
" is unrelated to this error)."
msgstr "Also remember to run Plone add-on installer for plone.app.z3cform (though it is unrelated to this error)."

# 52b49007ac6f46448416c47f1b058336
#: ../../source/troubleshooting/exceptions.rst:342
msgid "Case 2: missing plone.app.z3cform migration"
msgstr "Case 2: missing plone.app.z3cform migration"

# d001bebd93324c74a11dfc775e4803c3
#: ../../source/troubleshooting/exceptions.rst:358
msgid ""
"You are running Plone 4 with ``plone.app.directives`` form which does not "
"open. The reason is that you most likely have old ``plone.app.z3cform`` "
"installation which is not upgraded properly. In particular, the following "
"layer is missing"
msgstr "You are running Plone 4 with ``plone.app.directives`` form which does not open. The reason is that you most likely have old ``plone.app.z3cform`` installation which is not upgraded properly. In particular, the following layer is missing"

# b4a6caec3d3746ca90f2a4faafb32155
#: ../../source/troubleshooting/exceptions.rst:367
msgid "This enables ``z3c.form`` widgets on a Plone site."
msgstr "This enables ``z3c.form`` widgets on a Plone site."

# 119660cb05434d2d8c827015cc164a64
#: ../../source/troubleshooting/exceptions.rst:369
msgid ""
"Solution: *portal_setup* > *Import*. Choose profile *Plone z3cform support*."
" and import. The layer gets properly inserted to your site database."
msgstr "Solution: *portal_setup* > *Import*. Choose profile *Plone z3cform support*. and import. The layer gets properly inserted to your site database."

# 8b5d65e68ae0472e9555e12c49e5122c
#: ../../source/troubleshooting/exceptions.rst:373
msgid "NotFound error (Page not found) when accessing @@manage-portlets"
msgstr "NotFound error (Page not found) when accessing @@manage-portlets"

# 73a36a81e2c44f5db9f721825bbe3f4c
#: ../../source/troubleshooting/exceptions.rst:375
msgid ""
"If you get *Page not found* error when accessing @@manage-portlets the first"
" thing you need to do is to enable logging of NotFound exceptions in ZMI in "
"error_log."
msgstr "If you get *Page not found* error when accessing @@manage-portlets the first thing you need to do is to enable logging of NotFound exceptions in ZMI in error_log."

# b5605067c54d4bd7859eae83dda1b511
#: ../../source/troubleshooting/exceptions.rst:378
msgid "After that reload @@manage-portlets."
msgstr "After that reload @@manage-portlets."

# df19372eaa7346049477668f222c9cde
#: ../../source/troubleshooting/exceptions.rst:380
msgid ""
"When you try to access @@manage-portlets an exception a NotFound exception "
"is raised::"
msgstr "When you try to access @@manage-portlets an exception a NotFound exception is raised::"

# f3e0f732f9c6406a8354a879184668ed
#: ../../source/troubleshooting/exceptions.rst:439
msgid ""
"This usually means that your site has an portlet assignment which code is "
"not present anymore."
msgstr "This usually means that your site has an portlet assignment which code is not present anymore."

# 7c3868f1d6ff4f79b785749b30ded5f5
#: ../../source/troubleshooting/exceptions.rst:441
msgid ""
"In this case you can see that portlet type "
"\"collective.easytemplate.TemplatedPortlet\" is missing."
msgstr "In this case you can see that portlet type \"collective.easytemplate.TemplatedPortlet\" is missing."

# 3183cc266abc4d9baea26aecc426ca47
#: ../../source/troubleshooting/exceptions.rst:443
msgid ""
"Ä Check that you include the corresponding product (collective.easytemplate)"
" in eggs= section in buildout.cfg"
msgstr "Ä Check that you include the corresponding product (collective.easytemplate) in eggs= section in buildout.cfg"

# db145a1e30f140f48440b5afad282e7b
#: ../../source/troubleshooting/exceptions.rst:445
msgid "Reinstall removed egg which has the code for the portlet"
msgstr "Reinstall removed egg which has the code for the portlet"

# 349aceebb68c4369a0d448b438220fca
#: ../../source/troubleshooting/exceptions.rst:447
msgid ""
"Check that you include the corresponding product (collective.easytemplate) "
"in zcml= section in buildout.cfg"
msgstr "Check that you include the corresponding product (collective.easytemplate) in zcml= section in buildout.cfg"

# d5649492da294f29a5f77fb32194e406
#: ../../source/troubleshooting/exceptions.rst:449
msgid "Make sure that portlet name is the same in ZCML and GenericSetup XML"
msgstr "Make sure that portlet name is the same in ZCML and GenericSetup XML"

# 4d8c1f6ae3d34cabbbca3c85ddc1f0d0
#: ../../source/troubleshooting/exceptions.rst:451
msgid "Make sure you use <include package=\".portlets\" /> in your code"
msgstr "Make sure you use <include package=\".portlets\" /> in your code"

# 50667fc28e954907866e0684d7ccdae7
#: ../../source/troubleshooting/exceptions.rst:454
msgid "Manually removing the portlet"
msgstr "Manually removing the portlet"

# a7cc961da0274769a8283111b7dc12e8
#: ../../source/troubleshooting/exceptions.rst:456
msgid "If you have a traceback like this::"
msgstr "If you have a traceback like this::"

# 43266a0e70f2457c9b480769b9695788
#: ../../source/troubleshooting/exceptions.rst:487
msgid ""
"It usually means that there is a portlet in your content which product code "
"has been removed."
msgstr "It usually means that there is a portlet in your content which product code has been removed."

# 1064b5c500bd41ed9ea7b4c564aaf6e2
#: ../../source/troubleshooting/exceptions.rst:489
msgid ""
"Reinstall the add-on providing the portlet, remove the portlet and then "
"uninstall the add-on again."
msgstr "Reinstall the add-on providing the portlet, remove the portlet and then uninstall the add-on again."

# 4519fcdc17be4666937b6be8d5aa17cf
#: ../../source/troubleshooting/exceptions.rst:492
msgid "AttributeError: getPhysicalPath()"
msgstr "AttributeError: getPhysicalPath()"

# b9198d11f48c4f0da025953500b1b38a
#: ../../source/troubleshooting/exceptions.rst:526
msgid "Another possibility::"
msgstr "Another possibility::"

# b7e95320820a4deea7065c657fb6d58d
#: ../../source/troubleshooting/exceptions.rst:530
msgid ""
"This usually means that you should have used context.aq_inner when you have "
"used context. absolute_url() tries to get the path to the object, but object"
" parent is set to view (context.aq_parent) instead of real container object "
"(context.aq_inner.aq_parent)."
msgstr "This usually means that you should have used context.aq_inner when you have used context. absolute_url() tries to get the path to the object, but object parent is set to view (context.aq_parent) instead of real container object (context.aq_inner.aq_parent)."

# a11a57c14f8547a2b2f1e7e831774a77
#: ../../source/troubleshooting/exceptions.rst:536
msgid ""
"When setting a member attribute in BrowserView, the acquisition parent of "
"objec changes to BrowserView instance. All member attributes receive "
"ImplicitAcquisitionWrapper automatically."
msgstr "When setting a member attribute in BrowserView, the acquisition parent of objec changes to BrowserView instance. All member attributes receive ImplicitAcquisitionWrapper automatically."

# 5b48c8fa099d49219c379c0196610017
#: ../../source/troubleshooting/exceptions.rst:540
msgid "Demonstration"
msgstr "Demonstration"

# 3d6dd17fd8d3470d92377f6bbfce4b0a
#: ../../source/troubleshooting/exceptions.rst:542
msgid ""
"We try to set BrowserView member attribute defining_context to be some "
"context object."
msgstr "We try to set BrowserView member attribute defining_context to be some context object."

# 7a72baae5fe64abb98e3853e85b641b3
#: ../../source/troubleshooting/exceptions.rst:544
msgid ""
"(Pdb) self.defining_context = context (Pdb) context.aq_parent <PloneSite at "
"/plone> (Pdb) self.defining_context.aq_parent "
"<Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750> (Pdb) "
"self.defining_context.aq_inner.aq_parent "
"<Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750> (Pdb) "
"self.defining_context.aq_parent.aq_parent <ATDocument at /plone/doc> (Pdb) "
"self.defining_context.aq_parent.aq_parent.aq_inner <ATDocument at "
"/plone/doc> (Pdb) self.defining_context.aq_parent.aq_parent.aq_parent "
"<PloneSite at /plone>"
msgstr "(Pdb) self.defining_context = context (Pdb) context.aq_parent <PloneSite at /plone> (Pdb) self.defining_context.aq_parent <Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750> (Pdb) self.defining_context.aq_inner.aq_parent <Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750> (Pdb) self.defining_context.aq_parent.aq_parent <ATDocument at /plone/doc> (Pdb) self.defining_context.aq_parent.aq_parent.aq_inner <ATDocument at /plone/doc> (Pdb) self.defining_context.aq_parent.aq_parent.aq_parent <PloneSite at /plone>"

# aeaee182f0fe47249c25475cd0312796
#: ../../source/troubleshooting/exceptions.rst:558
msgid ""
"To get the real object (as it was before set was called) you can create a "
"helper getter::"
msgstr "To get the real object (as it was before set was called) you can create a helper getter::"

# 86dd3987b3ad4bd49224dad0e19bd5aa
#: ../../source/troubleshooting/exceptions.rst:572
msgid ""
"RuntimeError: maximum recursion depth exceeded (Archetypes field problem)"
msgstr "RuntimeError: maximum recursion depth exceeded (Archetypes field problem)"

# 2c85a7c4248a48cd8887a0d539f881e6
#: ../../source/troubleshooting/exceptions.rst:604
msgid ""
"Reason: Schema fields using AttributeStorage (usually images, files) "
"**cannot** have ATFieldProperty in the class::"
msgstr "Reason: Schema fields using AttributeStorage (usually images, files) **cannot** have ATFieldProperty in the class::"

# 87a74a75b0b6484a87862dc5296ea459
#: ../../source/troubleshooting/exceptions.rst:611
msgid ""
"To fix this simply remobe ATFieldProperty() declaration for the problematic "
"field. You cannot access the field value anymore by calling "
"*object.memberimage* but you need to call *object.getMemberimage()* instead."
msgstr "To fix this simply remobe ATFieldProperty() declaration for the problematic field. You cannot access the field value anymore by calling *object.memberimage* but you need to call *object.getMemberimage()* instead."

# 8ffecd3afd974a0f8b4490a0b35acbc4
#: ../../source/troubleshooting/exceptions.rst:616
msgid "Invalid or Duplicate property id"
msgstr "Invalid or Duplicate property id"

# 82fd9d833fac4b6593ae0d6bc3175914
#: ../../source/troubleshooting/exceptions.rst:618
msgid ""
"The following exception may appear during Plone migration to the newer "
"version::"
msgstr "The following exception may appear during Plone migration to the newer version::"

# 2cf014a250cc4fc7a5a32f3ae6a5e7e9
#: ../../source/troubleshooting/exceptions.rst:678
msgid ""
"It is caused by a property (site setting) which already exists and migration"
" tries to create it. The usual reason is that one has edited site settings "
"in new Plone version before running the migration."
msgstr "It is caused by a property (site setting) which already exists and migration tries to create it. The usual reason is that one has edited site settings in new Plone version before running the migration."

# 19634aa2a7f447dd85fd45be9a5f27c2
#: ../../source/troubleshooting/exceptions.rst:681
msgid ""
"Try remove violating property ids from the site_properties manually in Zope."
msgstr "Try remove violating property ids from the site_properties manually in Zope."

# 78e07e47a937407ba489dd19504993f0
#: ../../source/troubleshooting/exceptions.rst:683
msgid "Potential candidates to be removed:"
msgstr "Potential candidates to be removed:"

# cd57bd0d4a064b918d69592b07892df5
#: ../../source/troubleshooting/exceptions.rst:685
msgid "enable_inline_editing"
msgstr "enable_inline_editing"

# a13368b15f23475d88d4eb1209dd022c
#: ../../source/troubleshooting/exceptions.rst:687
msgid "lock_on_ttw_edit (boolean)"
msgstr "lock_on_ttw_edit (boolean)"

# 4f75c98f59514572944c8892f9cea260
#: ../../source/troubleshooting/exceptions.rst:689
msgid "Potential candidates which need to be added manually:"
msgstr "Potential candidates which need to be added manually:"

# 154de2f70a504a68b9dc49b028ad3f58
#: ../../source/troubleshooting/exceptions.rst:691
msgid "redirect_links (boolean)"
msgstr "redirect_links (boolean)"

# e9ed538e7bc64d22bb65cf3a6bda7216
#: ../../source/troubleshooting/exceptions.rst:695
msgid "http://www.mail-archive.com/setup@lists.plone.org/msg03988.html"
msgstr "http://www.mail-archive.com/setup@lists.plone.org/msg03988.html"

# 7d9c983387604023a3837dfc4697198e
#: ../../source/troubleshooting/exceptions.rst:699
msgid "TraversalError: No traversable adapter found"
msgstr "TraversalError: No traversable adapter found"

# ea1e4e8142a4449f9da0453b2587d97c
#: ../../source/troubleshooting/exceptions.rst:701
msgid "Traceback (innermost last):"
msgstr "Traceback (innermost last):"

# acec8f16a39a48b2af177a117da121ee
#: ../../source/troubleshooting/exceptions.rst:703
msgid "Module ZPublisher.Publish, line 202, in publish_module_standard"
msgstr "Module ZPublisher.Publish, line 202, in publish_module_standard"

# 8717bbf08e3c45b79adc5a27e456fd65
#: ../../source/troubleshooting/exceptions.rst:704
msgid "Module Products.LinguaPlone.patches, line 66, in new_publish"
msgstr "Module Products.LinguaPlone.patches, line 66, in new_publish"

# 002e61f5190140f089a7c1abc539c6f8
#: ../../source/troubleshooting/exceptions.rst:705
msgid "Module ZPublisher.Publish, line 150, in publish"
msgstr "Module ZPublisher.Publish, line 150, in publish"

# 624c23a0d171450984310b4d15c82fd7
#: ../../source/troubleshooting/exceptions.rst:706
msgid "Module Zope2.App.startup, line 221, in zpublisher_exception_hook"
msgstr "Module Zope2.App.startup, line 221, in zpublisher_exception_hook"

# 480b4064703a4897bcd067d135cfea61
#: ../../source/troubleshooting/exceptions.rst:707
msgid "Module ZPublisher.Publish, line 119, in publish"
msgstr "Module ZPublisher.Publish, line 119, in publish"

# 90a9af67b17e41408771fb153b8da295
#: ../../source/troubleshooting/exceptions.rst:708
msgid "Module ZPublisher.mapply, line 88, in mapply"
msgstr "Module ZPublisher.mapply, line 88, in mapply"

# cb8f9ad9bf44412d8224002503530c5c
#: ../../source/troubleshooting/exceptions.rst:709
msgid "Module ZPublisher.Publish, line 42, in call_object"
msgstr "Module ZPublisher.Publish, line 42, in call_object"

# 4331afba2bdb4647894c169b9dedae5b
#: ../../source/troubleshooting/exceptions.rst:710
msgid "Module Shared.DC.Scripts.Bindings, line 313, in __call__"
msgstr "Module Shared.DC.Scripts.Bindings, line 313, in __call__"

# d2750595545e458b9d339620dc5bb15a
#: ../../source/troubleshooting/exceptions.rst:711
msgid "Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec"
msgstr "Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec"

# 7dce7f42bc0c4bb38002e12a4105328c
#: ../../source/troubleshooting/exceptions.rst:712
msgid "Module Products.CMFCore.FSPageTemplate, line 216, in _exec"
msgstr "Module Products.CMFCore.FSPageTemplate, line 216, in _exec"

# 35cd14898b774d4c8fd6d88178170dc0
#: ../../source/troubleshooting/exceptions.rst:713
msgid "Module Products.CMFCore.FSPageTemplate, line 155, in pt_render"
msgstr "Module Products.CMFCore.FSPageTemplate, line 155, in pt_render"

# 4304ada761fa42618b674fedb31386a7
#: ../../source/troubleshooting/exceptions.rst:714
msgid "Module Products.PageTemplates.PageTemplate, line 98, in pt_render"
msgstr "Module Products.PageTemplates.PageTemplate, line 98, in pt_render"

# 4f490a690a9549eda197d48bca4264a7
#: ../../source/troubleshooting/exceptions.rst:715
msgid ""
"Module zope.pagetemplate.pagetemplate, line 117, in pt_render Warning: Macro"
" expansion failed Warning: zope.traversing.interfaces.TraversalError: ('No "
"traversable adapter found',"
msgstr "Module zope.pagetemplate.pagetemplate, line 117, in pt_render Warning: Macro expansion failed Warning: zope.traversing.interfaces.TraversalError: ('No traversable adapter found',"

# b067b991454b49099b67f79541ac6e1a
#: ../../source/troubleshooting/exceptions.rst:720
msgid "This traceback is followed by long dump of template code internals."
msgstr "This traceback is followed by long dump of template code internals."

# b7348490118945e7a97b70633176a1bb
#: ../../source/troubleshooting/exceptions.rst:722
msgid "Usual cause: Some add-on product fails to initialize."
msgstr "Usual cause: Some add-on product fails to initialize."

# cf035727e9a843ac8261fe91c26090a4
#: ../../source/troubleshooting/exceptions.rst:724
msgid ""
"Start Zope in foreground mode (bin/instance fg) to see which product fails."
msgstr "Start Zope in foreground mode (bin/instance fg) to see which product fails."

# e9df087720e94fdcaab30a6408e2bc56
#: ../../source/troubleshooting/exceptions.rst:727
msgid "ImportError: Inappropriate file type for dynamic loading"
msgstr "ImportError: Inappropriate file type for dynamic loading"

# 6f9490da69264e9098e8d078696564fe
#: ../../source/troubleshooting/exceptions.rst:729
msgid "Exception when starting Zope::"
msgstr "Exception when starting Zope::"

# 436e614e0e8d4384b2cf446e54f44230
#: ../../source/troubleshooting/exceptions.rst:743
msgid "You probably have files lying over from wrong CPU architecture"
msgstr "You probably have files lying over from wrong CPU architecture"

# 56074dd4e75948bb8ff8db6369d871d7
#: ../../source/troubleshooting/exceptions.rst:745
msgid "Hand copied eggs between servers"
msgstr "Hand copied eggs between servers"

# 3e8af551263f4fef82900bcebf552599
#: ../../source/troubleshooting/exceptions.rst:747
msgid "Migrated OS to new version"
msgstr "Migrated OS to new version"

# dc2840c72e14437d82f0997d95e8a117
#: ../../source/troubleshooting/exceptions.rst:749
msgid ""
"You have several Python interpreters installed and you try to run Zope using"
" the wrong interpreter (the one which the code is not compiled for)"
msgstr "You have several Python interpreters installed and you try to run Zope using the wrong interpreter (the one which the code is not compiled for)"

# a13638a8034141b0a1d33b85f92c4fea
#: ../../source/troubleshooting/exceptions.rst:752
msgid "How to solve problem"
msgstr "How to solve problem"

# e9967bf7f75c47d9aea7a842012ce3d8
#: ../../source/troubleshooting/exceptions.rst:754
msgid "Delete /parts and /eggs buildout folders, run bootstrap, run buildout."
msgstr "Delete /parts and /eggs buildout folders, run bootstrap, run buildout."

# f8444894c7da42cbbf100e58296cd750
#: ../../source/troubleshooting/exceptions.rst:757
msgid "BadRequest: The id \"xxx\" is invalid - it is already in use."
msgstr "BadRequest: The id \"xxx\" is invalid - it is already in use."

# 4db27a583abb489cba387f93a98cd73c
# 9a11cad1472f4d13bb3da5762f8129ab
#: ../../source/troubleshooting/exceptions.rst:759
#: ../../source/troubleshooting/transactions.rst:293
msgid "Traceback example::"
msgstr "Traceback example::"

# fcc305a43e154329be9fa839d2f92740
#: ../../source/troubleshooting/exceptions.rst:789
msgid "Not really sure why this happens."
msgstr "Not really sure why this happens."

# 5d3f8ca783ae425b9d09bced0ef98490
#: ../../source/troubleshooting/exceptions.rst:791
msgid "Try portal_catalog rebuild as a fix."
msgstr "Try portal_catalog rebuild as a fix."

# d99fd05b301447a7b3b831e46da8754b
#: ../../source/troubleshooting/exceptions.rst:794
msgid "Exception: Type name not specified in createObject"
msgstr "Exception: Type name not specified in createObject"

# 7e68286746fd4d02874f4595c0c1b379
#: ../../source/troubleshooting/exceptions.rst:812
msgid "Complete"
msgstr "Complete"

# 42d1d848669d47f095aa3e4f390352e5
#: ../../source/troubleshooting/exceptions.rst:815
msgid "Unauthorized: The object is marked as private"
msgstr "Unauthorized: The object is marked as private"

# 1831d1c2e995409b9f86392932c63a91
#: ../../source/troubleshooting/exceptions.rst:817
msgid ""
"This error is raised when you try to access view functions or objects for a "
"view, which you call manually from the code."
msgstr "This error is raised when you try to access view functions or objects for a view, which you call manually from the code."

# a6896e41b3674f9da3050040bb1bbd30
#: ../../source/troubleshooting/exceptions.rst:840
msgid ""
"View acquisition chain is not properly set up and the security manager "
"cannot traverse acquisition chain parents to properly determine permissions."
msgstr "View acquisition chain is not properly set up and the security manager cannot traverse acquisition chain parents to properly determine permissions."

# 528a6e65942f445ca0a2dc75de558dbb
#: ../../source/troubleshooting/exceptions.rst:843
msgid ""
"You need to use __of__() method to set-up the acquisition chain for the "
"view::"
msgstr "You need to use __of__() method to set-up the acquisition chain for the view::"

# c85dae514a7243648f315faa23c41817
#: ../../source/troubleshooting/exceptions.rst:855
msgid "ImportError: No module named PIL"
msgstr "ImportError: No module named PIL"

# 5015d6bb2ba3461f9faa582c87565e6e
#: ../../source/troubleshooting/exceptions.rst:913
msgid ""
"Python Imaging Library is not properly installed. The default PIL package "
"does not work nicely as egg."
msgstr "Python Imaging Library is not properly installed. The default PIL package does not work nicely as egg."

# bf88f98ee34247ee888153f39f0190b9
#: ../../source/troubleshooting/exceptions.rst:915
msgid "Remove all existing PIL eggs from buildout/eggs folder."
msgstr "Remove all existing PIL eggs from buildout/eggs folder."

# 2d2f5658ad65463faf7c4535b648a200
#: ../../source/troubleshooting/exceptions.rst:917
msgid "Install PIL for your development Python environment::"
msgstr "Install PIL for your development Python environment::"

# 606beadf0fa341aa8779e6142438b514
#: ../../source/troubleshooting/exceptions.rst:922
msgid "NotFound while accessing a BrowserView based view"
msgstr "NotFound while accessing a BrowserView based view"

# 85aed2376cc24f4ebd093b8c92f08070
#: ../../source/troubleshooting/exceptions.rst:924
msgid ""
"You'll get a NotFound error when accessing view using view traverse "
"notation, event though the view exist."
msgstr "You'll get a NotFound error when accessing view using view traverse notation, event though the view exist."

# e001333b0dae4409a799fd6775c83c62
#: ../../source/troubleshooting/exceptions.rst:927
msgid "Example URL::"
msgstr "Example URL::"

# a1120f67cca6404ca19fbb56dcc2759a
#: ../../source/troubleshooting/exceptions.rst:939
msgid ""
"This is because there is an exception raised in your view's __init__() "
"method. Views are Zope multi-adapters. Exception in multi-adapter factory "
"method causes ComponentLookUpError. Zope 2 publisher translates this to "
"NotFound error."
msgstr "This is because there is an exception raised in your view's __init__() method. Views are Zope multi-adapters. Exception in multi-adapter factory method causes ComponentLookUpError. Zope 2 publisher translates this to NotFound error."

# 5c47180e524c4d4cbf150b85b05839e8
# eb3444a5590743a4a38b01d257b45466
#: ../../source/troubleshooting/exceptions.rst:944
#: ../../source/troubleshooting/unicode.rst:128
msgid "How to fix"
msgstr "How to fix"

# 2f5ead1c5a934558879992af475b295d
#: ../../source/troubleshooting/exceptions.rst:946
msgid ""
"Put :doc:`pdb break statement </testing_and_debugging/pdb>` to the beginning"
" of the __init__() method of your view. Then step through view code to see "
"where the exception is raisen."
msgstr "Put :doc:`pdb break statement </testing_and_debugging/pdb>` to the beginning of the __init__() method of your view. Then step through view code to see where the exception is raisen."

# 3d803a856d434dc6bd7ed518a2eafea4
#: ../../source/troubleshooting/exceptions.rst:949
msgid ""
"If your view does not have __init__() method, then copy the source code "
"__init__() method to your view class from the first parent class which has a"
" view"
msgstr "If your view does not have __init__() method, then copy the source code __init__() method to your view class from the first parent class which has a view"

# 8798061e37814fa8bade2ecf7c7dabae
#: ../../source/troubleshooting/exceptions.rst:953
msgid "ContentProviderLookupError: plone.htmlhead"
msgstr "ContentProviderLookupError: plone.htmlhead"

# c2e81c4c51f3411a94fbb8cb4b678277
#: ../../source/troubleshooting/exceptions.rst:980
msgid ""
"This is not a bug in Zope. It is caused by trying to render a Plone page "
"frame in an context which has not acquisition chain properly set up. Plone "
"``main_template.pt`` tries to look up viewlet managers by acquistion "
"traversing to parent objects. ``plone.htmlhead`` is the first viewlet "
"manager to be looked up like this, and it will fail firstly."
msgstr "This is not a bug in Zope. It is caused by trying to render a Plone page frame in an context which has not acquisition chain properly set up. Plone ``main_template.pt`` tries to look up viewlet managers by acquistion traversing to parent objects. ``plone.htmlhead`` is the first viewlet manager to be looked up like this, and it will fail firstly."

# ef4f045e9aa0487a9b9d899c5b60c9b4
#: ../../source/troubleshooting/exceptions.rst:986
msgid "Some possible causes"
msgstr "Some possible causes"

# 7ee9b82f6d1f409aa91efbf8e760d4d6
#: ../../source/troubleshooting/exceptions.rst:988
msgid ""
"You are trying to embed main_template inside form/view which is already "
"rendered in main_template frame. Please see how to :doc:`embed forms and "
"wrap forms manually </forms/z3c.form>`."
msgstr "You are trying to embed main_template inside form/view which is already rendered in main_template frame. Please see how to :doc:`embed forms and wrap forms manually </forms/z3c.form>`."

# 38bf0e9850714b00af1165acf34ab885
#: ../../source/troubleshooting/exceptions.rst:991
msgid ""
"You might be using wrong ViewPageTemplate import (Five vs. zope.pagetemplate"
" - explained elsewhere in this documentation)"
msgstr "You might be using wrong ViewPageTemplate import (Five vs. zope.pagetemplate - explained elsewhere in this documentation)"

# 27edd55c84004de398c993f8b2a056f1
#: ../../source/troubleshooting/exceptions.rst:993
msgid ""
"Make sure that you call __of__() method for views and other objects you "
"construct by hand which expects themselves to be in the acquisition chain "
"(normally discovered by traversing)"
msgstr "Make sure that you call __of__() method for views and other objects you construct by hand which expects themselves to be in the acquisition chain (normally discovered by traversing)"

# 4c09408a9080428385e7da303954492a
#: ../../source/troubleshooting/exceptions.rst:996
msgid "See"
msgstr "See"

# 5541921c1e3b49f9b733d301d5037921
#: ../../source/troubleshooting/exceptions.rst:998
msgid "https://bugs.launchpad.net/zope2/+bug/176566"
msgstr "https://bugs.launchpad.net/zope2/+bug/176566"

# d7eefb1f95814089b6c7f12472241e2d
#: ../../source/troubleshooting/exceptions.rst:1003
msgid "Error while installing a new portlet portlets.xml: unbound prefix"
msgstr "Error while installing a new portlet portlets.xml: unbound prefix"

# 285a4ad104b942eda792f7559869d1e1
#: ../../source/troubleshooting/exceptions.rst:1023
msgid "Answer:"
msgstr "Answer:"

# d0559dcdb7b54e4f8dab752585623bbe
#: ../../source/troubleshooting/exceptions.rst:1025
msgid ""
"You have ``i18n:attributes=\"title; description\"`` in your portlets.xml. "
"Remove it or declare i18n namespace in XML."
msgstr "You have ``i18n:attributes=\"title; description\"`` in your portlets.xml. Remove it or declare i18n namespace in XML."

# 5211b86623a54035af7e8492321fb742
#: ../../source/troubleshooting/exceptions.rst:1028
msgid "ImportError: Couldn't import ZPublisherEventsBackport"
msgstr "ImportError: Couldn't import ZPublisherEventsBackport"

# 66ff65e14604411ea312b6091da6534b
#: ../../source/troubleshooting/exceptions.rst:1030
msgid "The following traceback on instance start-up::"
msgstr "The following traceback on instance start-up::"

# d5bbc08bc5b6465984a37a6aa0c3227c
#: ../../source/troubleshooting/exceptions.rst:1042
msgid ""
"plone.postpublicationhook 1.1 depends on new package, "
"ZPublisherEventsBackport, for Plone 3.3. You eed to include them both in "
"your buildout. You need to include both eggs::"
msgstr "plone.postpublicationhook 1.1 depends on new package, ZPublisherEventsBackport, for Plone 3.3. You eed to include them both in your buildout. You need to include both eggs::"

# 7a012703331747d197e9dead3ce564f1
#: ../../source/troubleshooting/exceptions.rst:1050
msgid "ERROR ZODB.Connection Couldn't load state for 0x00"
msgstr "ERROR ZODB.Connection Couldn't load state for 0x00"

# 578336116cce4aae98438ec9a5078652
#: ../../source/troubleshooting/exceptions.rst:1052
msgid "The following traceback pops up when you try to start Zope::"
msgstr "The following traceback pops up when you try to start Zope::"

# e1a71244fa624c20b2b8ca0d5b2b143a
#: ../../source/troubleshooting/exceptions.rst:1076
msgid ""
"Data.fs might have been damaged. You might be using blobs with Plone 3 and "
"they don't work perfectly. . . . or a bunch other issues which generally "
"mean that your day is screwed."
msgstr "Data.fs might have been damaged. You might be using blobs with Plone 3 and they don't work perfectly. . . . or a bunch other issues which generally mean that your day is screwed."

# a8391b6cd7da4d81af8bc0c384f5351f
#: ../../source/troubleshooting/exceptions.rst:1079
msgid "See also"
msgstr "See also"

# 0c44cdff6db848cb85e34b4ca6d655f6
#: ../../source/troubleshooting/exceptions.rst:1081
msgid ""
"http://plonechix.blogspot.com/2009/12/definitive-guide-to-poskeyerror.html"
msgstr "http://plonechix.blogspot.com/2009/12/definitive-guide-to-poskeyerror.html"

# 309795abb76f473b83b426d9e82b82ff
#: ../../source/troubleshooting/exceptions.rst:1084
msgid "POSKeyError"
msgstr "POSKeyError"

# 0f50d011100d45eb8902ca27e1e5ef3e
#: ../../source/troubleshooting/exceptions.rst:1086
msgid ""
"POSKeyError is when the database has been unable to convert a reference to "
"an object into the object itself It's a low level error usually caused by a "
"corrupt or incomplete database."
msgstr "POSKeyError is when the database has been unable to convert a reference to an object into the object itself It's a low level error usually caused by a corrupt or incomplete database."

# d6e5c1b5dc6e43b5981cc6ddba5f8026
#: ../../source/troubleshooting/exceptions.rst:1089
msgid "You did not copy blobs when you copied Data.fs"
msgstr "You did not copy blobs when you copied Data.fs"

# b6047adc4fa84192bb1d436433104874
#: ../../source/troubleshooting/exceptions.rst:1091
msgid "Your data is corrupted"
msgstr "Your data is corrupted"

# b61471d232c64a7c8318ec22b28c8a30
#: ../../source/troubleshooting/exceptions.rst:1093
msgid "Glitch in database (very unlikely)"
msgstr "Glitch in database (very unlikely)"

# c9405456f4604b60a33f16ea71e0b033
#: ../../source/troubleshooting/exceptions.rst:1097
msgid "http://rpatterson.net/blog/poskeyerror-during-commit"
msgstr "http://rpatterson.net/blog/poskeyerror-during-commit"

# d681a49711324dfd9ac4bbf12e707ab4
#: ../../source/troubleshooting/exceptions.rst:1100
msgid "Zope suddenly dies on OSX without a reason"
msgstr "Zope suddenly dies on OSX without a reason"

# da3770ee5a574ea6b132dfb8384a32cb
#: ../../source/troubleshooting/exceptions.rst:1102
msgid ""
"Symptoms: you do a HTTP request to a Plone site running OSX. Zope quits "
"without a reason."
msgstr "Symptoms: you do a HTTP request to a Plone site running OSX. Zope quits without a reason."

# 74b9b71802eb4071a15eb391788f1d9c
#: ../../source/troubleshooting/exceptions.rst:1104
msgid ""
"Reason: Infinite recursion is not properly handled by Python on OSX. This is"
" because OSX C stack size is smaller than Python default stack size. The "
"underlying Python interpreter dies before being able to raise stack size "
"limit exception."
msgstr "Reason: Infinite recursion is not properly handled by Python on OSX. This is because OSX C stack size is smaller than Python default stack size. The underlying Python interpreter dies before being able to raise stack size limit exception."

# e5858f98476b4aeca2e9d0ecadf926e2
#: ../../source/troubleshooting/exceptions.rst:1108
msgid "**Workaround**"
msgstr "**Workaround**"

# 199340221b4447658e517d2e7639ae0c
#: ../../source/troubleshooting/exceptions.rst:1110
msgid ""
"Edit ``python-2.4/lib/python2.4/site.py`` or corresponding Python "
"interpreter ``site.py`` file (Python site installation customization file)."
msgstr "Edit ``python-2.4/lib/python2.4/site.py`` or corresponding Python interpreter ``site.py`` file (Python site installation customization file)."

# 6a567d4d39574e2883eed8ac9588000f
#: ../../source/troubleshooting/exceptions.rst:1113
msgid "Put in to the first code line::"
msgstr "Put in to the first code line::"

# 9fac9c7d27974d23af78372a0bad0a8e
#: ../../source/troubleshooting/exceptions.rst:1117
msgid ""
"This will force smaller Python stack not exceeding native OSX C stack. You "
"might want to test other values and report back the findings."
msgstr "This will force smaller Python stack not exceeding native OSX C stack. You might want to test other values and report back the findings."

# be84e4e02bd54c06a043de4c8e376e02
#: ../../source/troubleshooting/exceptions.rst:1120
msgid "More Information"
msgstr "More Information"

# ba1b99984979477ba8ecd13aad414c2c
#: ../../source/troubleshooting/exceptions.rst:1122
msgid ""
"http://blog.crowproductions.de/2008/12/14/a-buildout-to-tame-the-snake-pit/ "
"(comments)"
msgstr "http://blog.crowproductions.de/2008/12/14/a-buildout-to-tame-the-snake-pit/ (comments)"

# 7592828218c84238b17e8c30855d4919
#: ../../source/troubleshooting/exceptions.rst:1125
msgid "IOError: [Errno url error] unknown url type: 'https'"
msgstr "IOError: [Errno url error] unknown url type: 'https'"

# cc86aedafc3a4e98bd3a2815e6ae4691
#: ../../source/troubleshooting/exceptions.rst:1139
msgid ""
"Reason: Python and Python socket modules have not been compiled with SSL "
"support."
msgstr "Reason: Python and Python socket modules have not been compiled with SSL support."

# f1b324c4fe354e8c8b3c2fa3ee76e7b7
#: ../../source/troubleshooting/exceptions.rst:1141
msgid ""
"Make sure that you have SSL development libraries installed (Ubuntu/Debian "
"example)"
msgstr "Make sure that you have SSL development libraries installed (Ubuntu/Debian example)"

# 933478a50b644fc9938b2c2029899649
#: ../../source/troubleshooting/exceptions.rst:1147
msgid "Make sure that Python is built with SSL support"
msgstr "Make sure that Python is built with SSL support"

# 69b55588384b4a7e90f776a23c2bf1e9
#: ../../source/troubleshooting/exceptions.rst:1153
msgid "You can test Python after compilation::"
msgstr "You can test Python after compilation::"

# d4486eadc4cc4b3c84f518a1842c8c2a
#: ../../source/troubleshooting/exceptions.rst:1163
msgid "Also you might want try"
msgstr "Also you might want try"

# 5e398495b66c42ae9e7dec370aa7c98e
#: ../../source/troubleshooting/exceptions.rst:1170
msgid "TypeError: len() of unsized object in smtplib"
msgstr "TypeError: len() of unsized object in smtplib"

# ad1c936824c0417db3549092770930a5
#: ../../source/troubleshooting/exceptions.rst:1201
msgid ""
"Cause: Your SMTP password has been set empty. Please reset your SMTP "
"password in *Mail* control panel."
msgstr "Cause: Your SMTP password has been set empty. Please reset your SMTP password in *Mail* control panel."

# d4c5454db88d4223b7a2b5ca6c5347a1
#: ../../source/troubleshooting/exceptions.rst:1205
msgid ""
"http://plone.293351.n2.nabble.com/Plone-3-3-5-sending-emails-len-of-unsized-"
"object-error-NO-ESMTP-PASSWORD-tp5415484p5415484.html"
msgstr "http://plone.293351.n2.nabble.com/Plone-3-3-5-sending-emails-len-of-unsized-object-error-NO-ESMTP-PASSWORD-tp5415484p5415484.html"

# 84172cb687c1414c8e10489364fc6e14
#: ../../source/troubleshooting/exceptions.rst:1209
msgid "NameError: name 'test' is not defined"
msgstr "NameError: name 'test' is not defined"

# 1d341e353c9745d994b4a95d15562e0a
#: ../../source/troubleshooting/exceptions.rst:1211
msgid ""
"This exception occurs when you try to customize TAL page template code using"
" test() function. test() function has been dropped in Zope 3 page templates."
" You should no longer use test() function anywhere."
msgstr "This exception occurs when you try to customize TAL page template code using test() function. test() function has been dropped in Zope 3 page templates. You should no longer use test() function anywhere."

# e0262c9508ec40b5a4559083c97c4618
#: ../../source/troubleshooting/exceptions.rst:1215
msgid ""
"Solution: replace test() with common Python expression in your customized "
"template."
msgstr "Solution: replace test() with common Python expression in your customized template."

# 121326e809b945dba75f0936009dd9ea
#: ../../source/troubleshooting/exceptions.rst:1217
msgid "For example the orignal::"
msgstr "For example the orignal::"

# fbafc1d8a9d44902b70e32b34ba03892
#: ../../source/troubleshooting/exceptions.rst:1221
msgid "would need to be written as:"
msgstr "would need to be written as:"

# 6e8975c41a224b0b906f41df1f65019e
#: ../../source/troubleshooting/exceptions.rst:1223
msgid ""
"tal:attributes=\"class python:here.Format() in ('text/structured', "
"'text/x-rst', ) and 'stx' + kss_class or 'plain' + kss_class\""
msgstr "tal:attributes=\"class python:here.Format() in ('text/structured', 'text/x-rst', ) and 'stx' + kss_class or 'plain' + kss_class\""

# cd4c6d2246fd4ae09e2da6f453546427
#: ../../source/troubleshooting/exceptions.rst:1226
msgid "TraversalError(subject, name) in expressions"
msgstr "TraversalError(subject, name) in expressions"

# bc1f2e75b6b5443ebca78041972000b0
#: ../../source/troubleshooting/exceptions.rst:1228
msgid "You have traceback like::"
msgstr "You have traceback like::"

# 4846a8931b16400484254dcf4a4e32d9
#: ../../source/troubleshooting/exceptions.rst:1275
msgid ""
"From line ``Products/PageTemplates/Expressions.py`` you can see the error "
"comes from TAL templates. TAL templates are trying to execute path based "
"expressions."
msgstr "From line ``Products/PageTemplates/Expressions.py`` you can see the error comes from TAL templates. TAL templates are trying to execute path based expressions."

# 9357ee03edcc469ba51dce93a4d38dfd
#: ../../source/troubleshooting/exceptions.rst:1278
msgid ""
"If you can view this error through error_log the error_log traceback will "
"contain information what expression causes the exception. However if this "
"only happens with unit tests you can have something like::"
msgstr "If you can view this error through error_log the error_log traceback will contain information what expression causes the exception. However if this only happens with unit tests you can have something like::"

# ba78d774129d4698994450568c6218b6
#: ../../source/troubleshooting/exceptions.rst:1287
msgid "manually injected to ``zope.tales.expression`` module."
msgstr "manually injected to ``zope.tales.expression`` module."

# b3a95920f0d447c4a56f2be67ff0fbf9
#: ../../source/troubleshooting/exceptions.rst:1290
msgid ""
"Content status history won't render - traceback is content path reversed"
msgstr "Content status history won't render - traceback is content path reversed"

# f47dadef91f0458ba6dc690fac875f6d
#: ../../source/troubleshooting/exceptions.rst:1324
msgid "No solution"
msgstr "No solution"

# eada71f1f70049ed8d4618eb176b1e65
#: ../../source/troubleshooting/exceptions.rst:1327
msgid "AttributeError: 'module' object has no attribute 'HTTPSConnection'"
msgstr "AttributeError: 'module' object has no attribute 'HTTPSConnection'"

# 0806e026d17148908cc44d48a938590b
#: ../../source/troubleshooting/exceptions.rst:1329
msgid "Python has not been compiled with HTTPS support."
msgstr "Python has not been compiled with HTTPS support."

# aa8be28a4500454991bda89f0b1db27d
#: ../../source/troubleshooting/exceptions.rst:1331
msgid "Try installing your Python, for example, using minitage."
msgstr "Try installing your Python, for example, using minitage."

# de26e00269194d60a4114d13e017112a
#: ../../source/troubleshooting/exceptions.rst:1333
msgid "See :doc:`Python basics </getstarted/python>`."
msgstr "See :doc:`Python basics </getstarted/python>`."

# e18a3ed83fb34424b35453aaedd3a2ec
#: ../../source/troubleshooting/exceptions.rst:1337
msgid "LinguaPlone: ImportError: cannot import name permissions"
msgstr "LinguaPlone: ImportError: cannot import name permissions"

# 972a322d373b4f038a63d055d3c31442
#: ../../source/troubleshooting/exceptions.rst:1353
msgid ""
"This seems to be Plone 4 issue of some sort. Import Products.ATContentTypes "
"before importing LinguagePlone."
msgstr "This seems to be Plone 4 issue of some sort. Import Products.ATContentTypes before importing LinguagePlone."

# dadad479846142a78417a64b3f2461e9
# de4b14c645a149909e931f78935bbe9a
#: ../../source/troubleshooting/exceptions.rst:1356
#: ../../source/troubleshooting/exceptions.rst:1360
msgid "http://plone.org/products/linguaplone/issues/253"
msgstr "http://plone.org/products/linguaplone/issues/253"

# f6c67c76e0884d84b6ab96cdf22e2dd5
#: ../../source/troubleshooting/exceptions.rst:1358
msgid "Related"
msgstr "Related"

# c11ba7f32ee34b809373e280c3c1ddc8
#: ../../source/troubleshooting/exceptions.rst:1363
msgid "TypeError: 'NoneType' object is not callable during upgrade"
msgstr "TypeError: 'NoneType' object is not callable during upgrade"

# ea1686d9834e4053ae22ed5b33b7d143
#: ../../source/troubleshooting/exceptions.rst:1365
msgid "Traceback during add-on install run / site upgrade::"
msgstr "Traceback during add-on install run / site upgrade::"

# 943f3bbf0f25436998206b9b245d99e5
#: ../../source/troubleshooting/exceptions.rst:1382
msgid ""
"This means that your site database contains installed add-on utility objects"
" for which Python code is no longer present."
msgstr "This means that your site database contains installed add-on utility objects for which Python code is no longer present."

# 76815f1ea5054ed295edc029a5eafae3
#: ../../source/troubleshooting/exceptions.rst:1385
msgid "More pointers for resolving the tool can be found using pdb::"
msgstr "More pointers for resolving the tool can be found using pdb::"

# 0bc1d5c995d44e8987a3865efedf182c
#: ../../source/troubleshooting/exceptions.rst:1390
msgid ""
"This happens when you have used Singing and Dancing news letter product. "
"This add-on is problematic and does not uninstall cleanly."
msgstr "This happens when you have used Singing and Dancing news letter product. This add-on is problematic and does not uninstall cleanly."

# 480477c0c4304fd5a297d3863df58767
#: ../../source/troubleshooting/exceptions.rst:1393
msgid "Reinstall Singing & Dancing"
msgstr "Reinstall Singing & Dancing"

# 33230a88d7c741048eafc5934750adce
#: ../../source/troubleshooting/exceptions.rst:1395
msgid "Uninstall Singing & Dancing"
msgstr "Uninstall Singing & Dancing"

# 2f1fcc3675674d39bbf0699f7b348f7e
#: ../../source/troubleshooting/exceptions.rst:1397
msgid "Hope your site works again"
msgstr "Hope your site works again"

# cdd7c4116e36479a9e4fdc1eb84d19a3
#: ../../source/troubleshooting/exceptions.rst:1403
msgid ""
"http://opensourcehacker.com/2011/06/01/plone-4-upgrade-results-and-steps/"
msgstr "http://opensourcehacker.com/2011/06/01/plone-4-upgrade-results-and-steps/"

# aa03e560f21b4d9eacc523d1475edd7e
#: ../../source/troubleshooting/exceptions.rst:1405
msgid "http://pypi.python.org/pypi/wildcard.fixpersistentutilities"
msgstr "http://pypi.python.org/pypi/wildcard.fixpersistentutilities"

# ac6170e807114a8c8678658274f9f8f0
#: ../../source/troubleshooting/exceptions.rst:1408
msgid "ImportError: No module named pkgutil"
msgstr "ImportError: No module named pkgutil"

# 95002e1ea13c4c6388650f3f3b0861d1
#: ../../source/troubleshooting/exceptions.rst:1420
msgid ""
"If you are using Eclipse, ``idelauncher.py`` has been updated for Plone 4."
msgstr "If you are using Eclipse, ``idelauncher.py`` has been updated for Plone 4."

# c2391ac781ad408f84b5b395b4cb4c35
#: ../../source/troubleshooting/exceptions.rst:1422
msgid "Remove ``bin/idelauncher.py`` from file system"
msgstr "Remove ``bin/idelauncher.py`` from file system"

# 9ef5757a2e874721981f6db0cc5f0201
#: ../../source/troubleshooting/exceptions.rst:1424
msgid ""
"Redownload it from `here <http://plone.org/documentation/kb/developing-"
"plone-with-eclipse/ide-compatible-launcher-script>`_"
msgstr "Redownload it from `here <http://plone.org/documentation/kb/developing-plone-with-eclipse/ide-compatible-launcher-script>`_"

# 11220c6fb5574f199a79faa9417916e8
#: ../../source/troubleshooting/exceptions.rst:1426
msgid ""
"...or of you are using *collective.eclipsescripts* rerun command *Scripts ->"
" Plone -> Import src folder as workspace*"
msgstr "...or of you are using *collective.eclipsescripts* rerun command *Scripts -> Plone -> Import src folder as workspace*"

# f0fa9a65cc4047459438e7ede1f367a6
#: ../../source/troubleshooting/exceptions.rst:1429
msgid ""
"\"PicklingError: Can't pickle <class 'collective.singing.async.IQueue'>: "
"import of module collective.singing.async\""
msgstr "\"PicklingError: Can't pickle <class 'collective.singing.async.IQueue'>: import of module collective.singing.async\""

# 25b5e20bbb54464f9aaa4ce6cde91572
#: ../../source/troubleshooting/exceptions.rst:1431
msgid ""
"Singing & Dancing add-on does not uninstall cleanly. Try this command-line "
"script to get it fixed (not tested). Some parts may work, some not, "
"depending on how messed up your site is."
msgstr "Singing & Dancing add-on does not uninstall cleanly. Try this command-line script to get it fixed (not tested). Some parts may work, some not, depending on how messed up your site is."

# a55cbc61823f42f7b90548f68e216a8b
#: ../../source/troubleshooting/exceptions.rst:1434
msgid ""
"Note that you need to have S & D present in the buildout when running this "
"and then you can remove it afterwards::"
msgstr "Note that you need to have S & D present in the buildout when running this and then you can remove it afterwards::"

# c8ec3c67e04746d6b913ff1b610ce21d
#: ../../source/troubleshooting/exceptions.rst:1462
msgid "System lxml too old"
msgstr "System lxml too old"

# a1edeca82d6a49a6942f6fe0423d4cec
#: ../../source/troubleshooting/exceptions.rst:1464
msgid "Traceback when starting an instance::"
msgstr "Traceback when starting an instance::"

# b7cbce83527c44d18076cdce2d55429b
#: ../../source/troubleshooting/exceptions.rst:1476
msgid "Let's see if we are getting too old system wide lxml installation::"
msgstr "Let's see if we are getting too old system wide lxml installation::"

# cd93d940fa85404282ca8616db5bddf4
#: ../../source/troubleshooting/exceptions.rst:1494
msgid ""
"If we cannot fix the system lxml (your system software depends on it) the "
"only workaround is to create virtualenv. We cannot force Python 2.6, 2.5 or "
"2.4 not to use system libraries."
msgstr "If we cannot fix the system lxml (your system software depends on it) the only workaround is to create virtualenv. We cannot force Python 2.6, 2.5 or 2.4 not to use system libraries."

# 6ed37b0e6a3c48babd28e798f83f94c7
#: ../../source/troubleshooting/exceptions.rst:1501
msgid ""
"Include standalone lxml + libxml compilation in your ``buildout.cfg``::"
msgstr "Include standalone lxml + libxml compilation in your ``buildout.cfg``::"

# 808583342c404521984a2540379d1caa
#: ../../source/troubleshooting/exceptions.rst:1512
msgid ""
"If there are exiting lxml builds in buildout be sure they are removed::"
msgstr "If there are exiting lxml builds in buildout be sure they are removed::"

# 5befef97bc014001b3b2cc12d7d5ecf1
#: ../../source/troubleshooting/exceptions.rst:1516
msgid ""
"Then as the non-root re-bootstrap the buildout using non-system wide "
"Python::"
msgstr "Then as the non-root re-bootstrap the buildout using non-system wide Python::"

# 1f69f0786c224c35931ce0df229d389f
#: ../../source/troubleshooting/exceptions.rst:1524
msgid "... and after this it should no longer pull the bad system lxml."
msgstr "... and after this it should no longer pull the bad system lxml."

# b7c826ad2aed4706b61423bbadaa84c9
#: ../../source/troubleshooting/exceptions.rst:1527
msgid "TraversalError: @@standard_macros"
msgstr "TraversalError: @@standard_macros"

# 21a960730a2547c6bbb4d34cc88672b3
#: ../../source/troubleshooting/exceptions.rst:1565
msgid ""
":doc`Wrapping is missing from your form object </forms/z3c.form.txt>`. In "
"this case the following helped::"
msgstr ":doc`Wrapping is missing from your form object </forms/z3c.form.txt>`. In this case the following helped::"

# 8e2ce67ae1c74999a28d5bc5e57f04d0
#: ../../source/troubleshooting/exceptions.rst:1584
msgid "AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'"
msgstr "AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'"

# 28ec45e0e2574c76950f321932c0882f
#: ../../source/troubleshooting/exceptions.rst:1586
msgid "Traceback when starting Plone::"
msgstr "Traceback when starting Plone::"

# 6d2b2896a0364ba69a4ac84be3398b41
#: ../../source/troubleshooting/exceptions.rst:1596
msgid ""
"Cause: Trying to use Python 2.6 with Plone 3 - you need to use Python 2.4."
msgstr "Cause: Trying to use Python 2.6 with Plone 3 - you need to use Python 2.4."

# df57ce17ffbc41918cb2d95e1b485f2d
#: ../../source/troubleshooting/exceptions.rst:1599
msgid "getUtility() fails: ComponentLookupError"
msgstr "getUtility() fails: ComponentLookupError"

# 5595b0baebf44f0f8db9d9f02ecfd9cd
#: ../../source/troubleshooting/exceptions.rst:1601
msgid "Example exception::"
msgstr "Example exception::"

# 07cb3ad3dbe8436abff308abadea414e
#: ../../source/troubleshooting/exceptions.rst:1607
msgid ""
"Make sure that your class object implements in the utility interface in the "
"question::"
msgstr "Make sure that your class object implements in the utility interface in the question::"

# 7d894642c8ae4814ab93cc50f973406c
#: ../../source/troubleshooting/exceptions.rst:1614
msgid "AttributeError: REQUEST in getObject"
msgstr "AttributeError: REQUEST in getObject"

# 7084027c2bc948d08fadf086932d9c65
#: ../../source/troubleshooting/exceptions.rst:1637
msgid ""
"Reason: You are using command line script. getObject() fails for a catalog "
"brain, because the actual object is gone. However, unrestrictedTraverse() "
"does not handle this case gracefully."
msgstr "Reason: You are using command line script. getObject() fails for a catalog brain, because the actual object is gone. However, unrestrictedTraverse() does not handle this case gracefully."

# bfac3e391eb44382b189e0ed9ca77535
#: ../../source/troubleshooting/exceptions.rst:1642
msgid "get_language: 'NoneType' object has no attribute 'getLocaleID'"
msgstr "get_language: 'NoneType' object has no attribute 'getLocaleID'"

# a57f64106e114b5ebc10cae9293d73a2
#: ../../source/troubleshooting/exceptions.rst:1705
msgid ""
"Some sort of Products.CacheSetup related problem on Plone 3.3.x, hiding the "
"real error. Zope component architecture loading has failed (you are missing "
"critical bits). This is just the first entry where it tries to use an "
"unloaded code."
msgstr "Some sort of Products.CacheSetup related problem on Plone 3.3.x, hiding the real error. Zope component architecture loading has failed (you are missing critical bits). This is just the first entry where it tries to use an unloaded code."

# 0ee629b7d6e94a8398a32b057dbf7c60
#: ../../source/troubleshooting/exceptions.rst:1709
msgid ""
"Start your instance on the foreground and you should see the actual error."
msgstr "Start your instance on the foreground and you should see the actual error."

# bd9dc834359d41c7928bb045996de876
#: ../../source/troubleshooting/exceptions.rst:1712
msgid "Error _restore_index() when starting instance / ZEO server"
msgstr "Error _restore_index() when starting instance / ZEO server"

# a23b22fef4364dc984af684e2c37ec92
#: ../../source/troubleshooting/exceptions.rst:1756
msgid "Reason: Data.fs.index is corrupted."
msgstr "Reason: Data.fs.index is corrupted."

# 5798c69848b6427e957eb61abd6c8e56
#: ../../source/troubleshooting/exceptions.rst:1758
msgid ""
"Fix. Remove Data.fs.index file. The index will be rebuilt on the launch."
msgstr "Fix. Remove Data.fs.index file. The index will be rebuilt on the launch."

# e2f66d0caf464b00ade4c33d56ab6a61
#: ../../source/troubleshooting/exceptions.rst:1761
msgid "importToolset: TypeError: 'NoneType' object is not callable"
msgstr "importToolset: TypeError: 'NoneType' object is not callable"

# cb82140781434320ad526326660b90a6
#: ../../source/troubleshooting/exceptions.rst:1763
msgid ""
"This happens when you try to install an add-on product through Add-ons "
"configuration panel."
msgstr "This happens when you try to install an add-on product through Add-ons configuration panel."

# b11ef7bda18544dcb245ea956f3ddbfb
#: ../../source/troubleshooting/exceptions.rst:1779
msgid ""
"You have leftovers from some old add-on installation (persistent tool) and "
"Python egg code is no longer present for this tool."
msgstr "You have leftovers from some old add-on installation (persistent tool) and Python egg code is no longer present for this tool."

# 49ad4f2c0ae84bb29144f9575272195a
#: ../../source/troubleshooting/exceptions.rst:1782
msgid ""
"You should see a warning in logs giving you a hint when running add-on "
"installer::"
msgstr "You should see a warning in logs giving you a hint when running add-on installer::"

# 87a606eabdc143cb85f78261c3213951
#: ../../source/troubleshooting/exceptions.rst:1786
msgid "To fix this, see informatin below (Removing portal tools part)"
msgstr "To fix this, see informatin below (Removing portal tools part)"

# 9f92070e4a1345a281f08d094cbe1e71
#: ../../source/troubleshooting/exceptions.rst:1790
msgid "Example: start site debug shell::"
msgstr "Example: start site debug shell::"

# 2e467c7e151d426a91b8fb10997349d6
#: ../../source/troubleshooting/exceptions.rst:1794
msgid "Then run the script for your site id and problem tool id::"
msgstr "Then run the script for your site id and problem tool id::"

# 066d60dc15b544ceb58e03b7272701d9
#: ../../source/troubleshooting/exceptions.rst:1810
msgid ""
"In debug shell you can also check what all leftoverts toolset contains::"
msgstr "In debug shell you can also check what all leftoverts toolset contains::"

# 29a71bbb651e4e55a3e3323b81fa4389
#: ../../source/troubleshooting/exceptions.rst:1829
msgid ""
"http://plone.293351.n2.nabble.com/importToolset-NoneType-object-is-not-"
"callable-upon-product-install-td5553065.html"
msgstr "http://plone.293351.n2.nabble.com/importToolset-NoneType-object-is-not-callable-upon-product-install-td5553065.html"

# 130d1344eede47eb905d810fb91a3a14
#: ../../source/troubleshooting/exceptions.rst:1833
msgid "from zopeskel.basic_namespace import BasicNamespace"
msgstr "from zopeskel.basic_namespace import BasicNamespace"

# a26c7a4249534724acc545e27897bedf
#: ../../source/troubleshooting/exceptions.rst:1835
msgid "When starting ZopeSkel::"
msgstr "When starting ZopeSkel::"

# 6ffad9eca7a04d219c4656f87c31e357
#: ../../source/troubleshooting/exceptions.rst:1842
msgid "Or on paster with local commands::"
msgstr "Or on paster with local commands::"

# 738f7e285b664e55a26d065bf06cf7bc
#: ../../source/troubleshooting/exceptions.rst:1850
msgid ""
"System-wide templer / paster / zopeskel installation is affecting your "
"buildout installation."
msgstr "System-wide templer / paster / zopeskel installation is affecting your buildout installation."

# fd26604bb2e34bf49328b89e70de2f5e
#: ../../source/troubleshooting/exceptions.rst:1852
msgid "Remove system-wide installation::"
msgstr "Remove system-wide installation::"

# 1d1bc39e51ad4c6fa3f02372a8aedd3c
#: ../../source/troubleshooting/exceptions.rst:1856
msgid "Re-run buildout."
msgstr "Re-run buildout."

# 9dd3b6973d664267ac0e154de8140339
#: ../../source/troubleshooting/exceptions.rst:1858
msgid "Enjoy."
msgstr "Enjoy."

# 44eecd03bb0a42ec86a84a5153a83187
#: ../../source/troubleshooting/exceptions.rst:1861
msgid "'ExtensionClass.ExtensionClass' object is not iterable"
msgstr "'ExtensionClass.ExtensionClass' object is not iterable"

# 325d82cbe2d14dd7ba9d9bd561c4c9f2
#: ../../source/troubleshooting/exceptions.rst:1863
msgid ""
"This error tends to happen after moving a Data.fs to a new instance that "
"does not have the identical add-ons to the original instance."
msgstr "This error tends to happen after moving a Data.fs to a new instance that does not have the identical add-ons to the original instance."

# b84771816d8d4db9a699e7f57eee64fc
#: ../../source/troubleshooting/exceptions.rst:1888
msgid ""
"In this example traceback the missing add-on is Products.Carousel which "
"provides the marker interface Products.Carousel.interfaces.ICarousel"
msgstr "In this example traceback the missing add-on is Products.Carousel which provides the marker interface Products.Carousel.interfaces.ICarousel"

# 06cea827444d4511897af48e60ba44a3
#: ../../source/troubleshooting/exceptions.rst:1890
msgid "Solution: Install the missing add-on(s)"
msgstr "Solution: Install the missing add-on(s)"

# 73edb7f687b94dceb8542d9a161e5c93
#: ../../source/troubleshooting/exceptions.rst:1894
msgid "AttributeError: type object 'IRAMCache' has no attribute '__iro__'"
msgstr "AttributeError: type object 'IRAMCache' has no attribute '__iro__'"

# 19146ca59bf04e8d9e0b3cf5676b28c8
#: ../../source/troubleshooting/exceptions.rst:1896
msgid "Traceback when trying to open any page::"
msgstr "Traceback when trying to open any page::"

# 079b779ef63e47e5b45d17d1949fd66c
#: ../../source/troubleshooting/exceptions.rst:1914
msgid ""
"You have probably imported a Data.fs using newer Plone/Zope version to old "
"Plone, or package pindowns are incorrect. If you are copying a site try re-"
"checking that source and target buildouts and package versions match."
msgstr "You have probably imported a Data.fs using newer Plone/Zope version to old Plone, or package pindowns are incorrect. If you are copying a site try re-checking that source and target buildouts and package versions match."

# f79a04372c04427ab7b6b799d001f494
#: ../../source/troubleshooting/exceptions.rst:1919
msgid ""
"Unknown message (kss optimized for production mode) in Javascript console"
msgstr "Unknown message (kss optimized for production mode) in Javascript console"

# a8431b26811f4fc7939b69c944a510c7
#: ../../source/troubleshooting/exceptions.rst:1921
msgid ""
"This is a KSS error message. KSS is an technology used in Plone 3 and "
"started to be phased out in Plone 4."
msgstr "This is a KSS error message. KSS is an technology used in Plone 3 and started to be phased out in Plone 4."

# 7c92896bf61c4635991c9b49095c280f
#: ../../source/troubleshooting/exceptions.rst:1924
msgid "Possible causes are"
msgstr "Possible causes are"

# 8f9858ab941c47ffa92c76076ec69a26
#: ../../source/troubleshooting/exceptions.rst:1926
msgid "Problems with KSS files (see portal_kss registry)"
msgstr "Problems with KSS files (see portal_kss registry)"

# af72ef5a77594d5893622a1aeeabe548
#: ../../source/troubleshooting/exceptions.rst:1928
msgid "Browser bugs (Google around for the fixes)"
msgstr "Browser bugs (Google around for the fixes)"

# edacac8eef2744baa14ef726adc09050
#: ../../source/troubleshooting/exceptions.rst:1930
msgid "What you can do:"
msgstr "What you can do:"

# 1821bd5e80444977bafedbaebe0e8d37
#: ../../source/troubleshooting/exceptions.rst:1932
msgid "Go to portal_kss"
msgstr "Go to portal_kss"

# 9da4d9a0530a478696c9d2c82d252653
#: ../../source/troubleshooting/exceptions.rst:1934
msgid "Remove are stale entries (missing files, marked on red)"
msgstr "Remove are stale entries (missing files, marked on red)"

# 6029c3da0f2b4cc0bd40db35ac48ceee
#: ../../source/troubleshooting/exceptions.rst:1936
msgid "Also:"
msgstr "Also:"

# 9767b88b16ae4ae8b548796c4c149c97
#: ../../source/troubleshooting/exceptions.rst:1938
msgid "Put portal_kss for debug mode (in development environment)"
msgstr "Put portal_kss for debug mode (in development environment)"

# 8f5c7a8252c647fb8e03068ce6a4f60f
#: ../../source/troubleshooting/exceptions.rst:1941
msgid "ComponentLookupError: cmf.ManagePortal"
msgstr "ComponentLookupError: cmf.ManagePortal"

# f0fd4bb854c7424a8155190a7d7ed75d
#: ../../source/troubleshooting/exceptions.rst:1943
msgid "When starting Plone you'll get::"
msgstr "When starting Plone you'll get::"

# e28b2c3ad4154794b6a8462c7e5150b2
#: ../../source/troubleshooting/exceptions.rst:1949
msgid ""
"This is a sign of changed loading order, starting from Plone 4.1. You need "
"to explicitly include *CMFCore/permissions.zcml* in your "
"*configuration.zcml*."
msgstr "This is a sign of changed loading order, starting from Plone 4.1. You need to explicitly include *CMFCore/permissions.zcml* in your *configuration.zcml*."

# 25ee6b0fcff8475a82416dbe16fe2da9
#: ../../source/troubleshooting/exceptions.rst:1958
msgid "http://dev.plone.org/ticket/11837"
msgstr "http://dev.plone.org/ticket/11837"

# 47c10e38250249ad9df6efcc9a74782d
#: ../../source/troubleshooting/exceptions.rst:1962
msgid "AttributeError: Schema"
msgstr "AttributeError: Schema"

# 1f3bffb971b74b938dd0d0e3a66a3fd4
#: ../../source/troubleshooting/exceptions.rst:1964
msgid ""
"The following traceback comes when you try to view your custom content "
"type::"
msgstr "The following traceback comes when you try to view your custom content type::"

# 46460bac4f9c4beabc6907c52aae3ebb
#: ../../source/troubleshooting/exceptions.rst:1989
msgid ""
"Reason: It is picking up Archetypes default view template for your Dexterity"
" content type."
msgstr "Reason: It is picking up Archetypes default view template for your Dexterity content type."

# 0717c0100a014889ac3b4644c040f75b
#: ../../source/troubleshooting/exceptions.rst:1991
msgid ""
"Try if you can access your view by a directly calling it to by its name. "
"E.g.::"
msgstr "Try if you can access your view by a directly calling it to by its name. E.g.::"

# 95cd657bb67c4e7280f22ba133536aa8
#: ../../source/troubleshooting/exceptions.rst:1995
msgid "If it's working then it is wrong data in *portal_types*."
msgstr "If it's working then it is wrong data in *portal_types*."

# 5ed9e75bad534211b02960c3ee483d2c
#: ../../source/troubleshooting/exceptions.rst:1997
msgid ""
"Your content item might also be corrupted. It is trying to use dynamic view "
"selector even if it's not supported. Try re-creating the particular content "
"item."
msgstr "Your content item might also be corrupted. It is trying to use dynamic view selector even if it's not supported. Try re-creating the particular content item."

# 9bc2f4a35f1a4f32b76557dcf05842fb
#: ../../source/troubleshooting/exceptions.rst:2002
msgid "Error: Incorrect padding"
msgstr "Error: Incorrect padding"

# 7e467cc45cdb4ca6860a96a55552d9ef
#: ../../source/troubleshooting/exceptions.rst:2004
msgid "Traceback comes when you try to access any Plone site URL::"
msgstr "Traceback comes when you try to access any Plone site URL::"

# ed48a6df63d54091bdfa39e8c8de1543
#: ../../source/troubleshooting/exceptions.rst:2016
msgid ""
"It means that your browser most likely tries to serve bad cookies / auth "
"info to Zope. Clear browser cache, cookies, etc."
msgstr "It means that your browser most likely tries to serve bad cookies / auth info to Zope. Clear browser cache, cookies, etc."

# 0cd557fa3eec4253b965c9f6918e1692
#: ../../source/troubleshooting/exceptions.rst:2020
msgid "ValueError: Non-zero version length. Versions aren't supported."
msgstr "ValueError: Non-zero version length. Versions aren't supported."

# 295ad717c8974d9db282ba6d6aacc449
#: ../../source/troubleshooting/exceptions.rst:2022
msgid "When trying to open any page::"
msgstr "When trying to open any page::"

# bc704b4faa8b41b1ad9f4eab1015a9a1
#: ../../source/troubleshooting/exceptions.rst:2038
msgid ""
"Most likely a corrupted Data.fs. Stop zeoserver. Recopy Data.fs. Recopy "
"blobs."
msgstr "Most likely a corrupted Data.fs. Stop zeoserver. Recopy Data.fs. Recopy blobs."

# de51c52eae1a43748feeea985e018895
#: ../../source/troubleshooting/exceptions.rst:2042
msgid ""
"http://stackoverflow.com/questions/8387902/plone-upgrade-3-3-5-to-"
"plone-4-1-2"
msgstr "http://stackoverflow.com/questions/8387902/plone-upgrade-3-3-5-to-plone-4-1-2"

# 8356a3a63bfd4aee9c06d5919600e1b1
#: ../../source/troubleshooting/exceptions.rst:2044
msgid "https://mail.zope.org/pipermail/zodb-dev/2010-September/013620.html"
msgstr "https://mail.zope.org/pipermail/zodb-dev/2010-September/013620.html"

# ef765167af8c4634b0b2d6c3c420ae2a
#: ../../source/troubleshooting/exceptions.rst:2048
msgid "TypeError: argument of type 'NoneType' is not iterable"
msgstr "TypeError: argument of type 'NoneType' is not iterable"

# 91eeb728d31e44d19fa2a636be761d87
#: ../../source/troubleshooting/exceptions.rst:2062
msgid ""
"Plone 3 > Plone 4 migration has not been run. Run the migration in "
"*portal_migrations* under ZMI."
msgstr "Plone 3 > Plone 4 migration has not been run. Run the migration in *portal_migrations* under ZMI."

# 5eb2feace11a43b68e17e530a672351c
#: ../../source/troubleshooting/exceptions.rst:2067
msgid "Archetypes: TypeError: getattr(): attribute name must be string"
msgstr "Archetypes: TypeError: getattr(): attribute name must be string"

# e1ecfe1d657d49e998087fdb2b21bd22
#: ../../source/troubleshooting/exceptions.rst:2078
msgid ""
"You might have used something else besides string or translation string to "
"define Archetypes widget name or description."
msgstr "You might have used something else besides string or translation string to define Archetypes widget name or description."

# fcb5223e82f64223891906ae68591b24
#: ../../source/troubleshooting/exceptions.rst:2083
msgid "InvalidInterface: Concrete attribute"
msgstr "InvalidInterface: Concrete attribute"

# 0dc737df9e184077915b1e8b2757e794
#: ../../source/troubleshooting/exceptions.rst:2085
msgid "Your ``zope.schema`` based schema breaks on Plone startup."
msgstr "Your ``zope.schema`` based schema breaks on Plone startup."

# 83f2e89bacd341b6a12da654aac17373
#: ../../source/troubleshooting/exceptions.rst:2096
msgid "You have extra comma in your schema. Like this::"
msgstr "You have extra comma in your schema. Like this::"

# e041b5ec74c44dadbd9ed94a340a189e
#: ../../source/troubleshooting/exceptions.rst:2109
msgid ""
"AttributeError: 'FilesystemResourceDirectory' object has no attribute "
"'absolute_url'"
msgstr "AttributeError: 'FilesystemResourceDirectory' object has no attribute 'absolute_url'"

# 9c000c5e56a14a9d80f87ec2d851988d
#: ../../source/troubleshooting/exceptions.rst:2130
msgid ""
"There is a not accessible filesystem ressource declared in your diazo "
"theme's html. Check that all js and css files are available."
msgstr "There is a not accessible filesystem ressource declared in your diazo theme's html. Check that all js and css files are available."

# 397c88bf675e43a28befbb927e381669
#: ../../source/troubleshooting/images.rst:3
msgid "Image troubleshooting"
msgstr "Image troubleshooting"

# 606ef9d52ab54c8689dc982d6d1cf5f8
#: ../../source/troubleshooting/images.rst:7
msgid "Problems with imaging libraries, image loading and image scaling."
msgstr "Problems with imaging libraries, image loading and image scaling."

# f010a019c2974b869336e823ac63095d
#: ../../source/troubleshooting/images.rst:12
msgid "How to test see if your Python Imaging set-up works"
msgstr "How to test see if your Python Imaging set-up works"

# 0f6201e7050242868ceec8448eec8d2f
#: ../../source/troubleshooting/images.rst:14
msgid ""
"Example how to check if Python, Python Imaging Library (PIL) and libjpeg are"
" correctly working together."
msgstr "Example how to check if Python, Python Imaging Library (PIL) and libjpeg are correctly working together."

# de3ae6313e774ead8da56e32e54caa88
#: ../../source/troubleshooting/images.rst:17
msgid "Get a sample image::"
msgstr "Get a sample image::"

# 2c24b3a4dd634d5aaa0edbe778fda188
#: ../../source/troubleshooting/images.rst:21
msgid ""
"Start Python with Zope libraries in PYTHONPATH or Plone debug shell "
"(latter)::"
msgstr "Start Python with Zope libraries in PYTHONPATH or Plone debug shell (latter)::"

# 1e762d699c6d42a7ab09db81fa06d821
#: ../../source/troubleshooting/images.rst:27
msgid "Run the following on the interactive Python prompt started above::"
msgstr "Run the following on the interactive Python prompt started above::"

# e1479ce557d845a7806fbaad99332708
#: ../../source/troubleshooting/images.rst:36
msgid "No Python exceptions should be risen."
msgstr "No Python exceptions should be risen."

# a63150f11d83481d9a70f3e6ec658077
#: ../../source/troubleshooting/images.rst:40
msgid "Images are not loading"
msgstr "Images are not loading"

# 28d6371ad45740239eb2136eb71ccfba
#: ../../source/troubleshooting/images.rst:42
msgid ""
"Plone is not loading images or resized images are not available is usually "
"caused by broken PIL installation: PIL used by Python virtual machine "
"driving Plone does not have proper native libraries (libjpeg) available to "
"perform imaging operations."
msgstr "Plone is not loading images or resized images are not available is usually caused by broken PIL installation: PIL used by Python virtual machine driving Plone does not have proper native libraries (libjpeg) available to perform imaging operations."

# d05f38ade302434596d7ca4d5f0367f8
#: ../../source/troubleshooting/images.rst:46
msgid "If you run Zope on foreground you usually see errors like this::"
msgstr "If you run Zope on foreground you usually see errors like this::"

# 4e3aaf01fdf64e40b0693194e5d4b1ad
#: ../../source/troubleshooting/images.rst:65
msgid ""
"In the above case PYTHONPATH incorrectly tries to load Python 2.5 libraries,"
" though Plone 3.x exclusively uses Python 2.4. In this case the proper fix "
"is to clean-up damaged start up scripts in bin/ folder::"
msgstr "In the above case PYTHONPATH incorrectly tries to load Python 2.5 libraries, though Plone 3.x exclusively uses Python 2.4. In this case the proper fix is to clean-up damaged start up scripts in bin/ folder::"

# e8960499611c4104a0fb0ef918ec05bb
#: ../../source/troubleshooting/images.rst:74
msgid "This can be achieved by"
msgstr "This can be achieved by"

# 7cc72dce6d914d399045424032b68400
#: ../../source/troubleshooting/images.rst:76
msgid "Removed all py2.5 eggs under eggs/ folder"
msgstr "Removed all py2.5 eggs under eggs/ folder"

# 16ddd264da25480ab7d15dcd241fbe23
#: ../../source/troubleshooting/images.rst:78
msgid "Removing setuptools egg which may contain references to Python 2.5"
msgstr "Removing setuptools egg which may contain references to Python 2.5"

# 04b28d26847943da8a2d66f649fdf637
#: ../../source/troubleshooting/images.rst:80
msgid "Running bootstrap.py using python2.4"
msgstr "Running bootstrap.py using python2.4"

# 498d39100f874e88851144efbe1d6bfe
#: ../../source/troubleshooting/images.rst:82
msgid "Rerunning buildout after this"
msgstr "Rerunning buildout after this"

# f56b6661302646b5a3b27d2e34ffca27
#: ../../source/troubleshooting/images.rst:84
msgid ""
"For further debugging the problem you can start the particular Python "
"interpreter and try to import _imaging yourself."
msgstr "For further debugging the problem you can start the particular Python interpreter and try to import _imaging yourself."

# ae8441474f83493c813eb3e0fafb02e5
#: ../../source/troubleshooting/images.rst:86
msgid ""
"Run Python in verbose mode to print all imports (the example below has been "
"shortened)::"
msgstr "Run Python in verbose mode to print all imports (the example below has been shortened)::"

# 718336b42a3b4074bfaa085f37e50747
#: ../../source/troubleshooting/images.rst:98
msgid ""
"In this case we have a custom Python build based on "
"`collective.buildout.python <http://blog.mfabrik.com/2010/07/16/easily-"
"install-all-python-versions-under-linux-and-osx-using-collective-buildout-"
"python/>`_ recipe. It will compile us a custom libjpeg version and should "
"not use OS libjpeg::"
msgstr "In this case we have a custom Python build based on `collective.buildout.python <http://blog.mfabrik.com/2010/07/16/easily-install-all-python-versions-under-linux-and-osx-using-collective-buildout-python/>`_ recipe. It will compile us a custom libjpeg version and should not use OS libjpeg::"

# 099b65b8c3064033989df84e1d574a4e
#: ../../source/troubleshooting/images.rst:108
msgid ""
"However, looks like this libjpeg does not end up in the OS LD_LIBRARY_PATH "
"import list automatically."
msgstr "However, looks like this libjpeg does not end up in the OS LD_LIBRARY_PATH import list automatically."

# 47fe3e8478964517a6cff60b8d018629
#: ../../source/troubleshooting/images.rst:112
msgid ""
"http://permalink.gmane.org/gmane.comp.web.zope.plone.product-developers/4946"
msgstr "http://permalink.gmane.org/gmane.comp.web.zope.plone.product-developers/4946"

# f2dc65c55cf94f0caf68fafb8d62b4a3
#: ../../source/troubleshooting/images.rst:115
msgid "IOError when scaling images on Plone 4"
msgstr "IOError when scaling images on Plone 4"

# ac762f40807644b1aba3516db994eca5
#: ../../source/troubleshooting/images.rst:130
msgid ""
"This means that libjpeg setup is not working. See above to how to test your "
"set-up."
msgstr "This means that libjpeg setup is not working. See above to how to test your set-up."

# d9ca612425534c339031d82187f3b27e
#: ../../source/troubleshooting/images.rst:133
msgid "Installing libraries on Ubuntu / Debian"
msgstr "Installing libraries on Ubuntu / Debian"

# fc8d4dd72cf2496fa6ea962ac297c395
#: ../../source/troubleshooting/images.rst:135
msgid ""
"This applies if you are using system Python to run Plone. Version may vary "
"so ``apt-cache search`` and ``grep`` commands are your friends::"
msgstr "This applies if you are using system Python to run Plone. Version may vary so ``apt-cache search`` and ``grep`` commands are your friends::"

# f6254675f59d444c8d83ddeda835ee9c
#: ../../source/troubleshooting/images.rst:142
msgid "Forcing libjpeg path"
msgstr "Forcing libjpeg path"

# ac3ee4f00a014014b4111420d9640a17
#: ../../source/troubleshooting/images.rst:144
msgid "Try in buildout.cfg::"
msgstr "Try in buildout.cfg::"

# 83faa4b166c54ac489708285fbe10808
#: ../../source/troubleshooting/images.rst:153
msgid ""
"libjpeg.so.8: cannot open shared object file: No such file or directory"
msgstr "libjpeg.so.8: cannot open shared object file: No such file or directory"

# 427a5d8c455f4d7a8b6bde7ac432ecab
#: ../../source/troubleshooting/images.rst:155
msgid "On Ubuntu you'll get this error when you try::"
msgstr "On Ubuntu you'll get this error when you try::"

# f2978391bad643529bdc162f31806841
#: ../../source/troubleshooting/images.rst:160
msgid "Some tips"
msgstr "Some tips"

# ce66181f37594ace9c2ca680aea0887b
#: ../../source/troubleshooting/images.rst:162
msgid ""
"http://stackoverflow.com/questions/5545580/pil-libjpeg-so-8-cannot-open-"
"shared-object-file-no-such-file-or-directory"
msgstr "http://stackoverflow.com/questions/5545580/pil-libjpeg-so-8-cannot-open-shared-object-file-no-such-file-or-directory"

# 65f00dbf764b41bb83cff02e974f7162
#: ../../source/troubleshooting/transactions.rst:3
msgid "Database and transactions troubleshooting"
msgstr "Database and transactions troubleshooting"

# 05b486b86a9a4ebf8920a33c8fd33c75
#: ../../source/troubleshooting/transactions.rst:7
msgid "How to debug and fix ZODB database problems in Plone"
msgstr "How to debug and fix ZODB database problems in Plone"

# bd36f9736c3b4a31b233a035da9c559a
#: ../../source/troubleshooting/transactions.rst:14
msgid ""
"This document contains information to fix and debug ZODB databases with "
"Plone."
msgstr "This document contains information to fix and debug ZODB databases with Plone."

# 6d3155c03dba4c04a085b2ea0c2eab71
#: ../../source/troubleshooting/transactions.rst:17
msgid "BLOBs and POSKeyErrors"
msgstr "BLOBs and POSKeyErrors"

# b2a6b67b79894dbbbc49927f0cccf876
#: ../../source/troubleshooting/transactions.rst:19
msgid ""
"The `Plone CMS <http://plone.org>`_ from version 4.x onwards stores files "
"and images uploaded to the `ZODB <http://www.zodb.org/>`_ as `BLOBs "
"<http://www.zodb.org/zodbbook/introduction.html?highlight=blob#blobs>`_. "
"They exist in a ``var/blobstorage`` folder structure on the file system, "
"files being named after (opaque) persistent object ids. When using the "
"default backend, the objects themselves, without file payload, are stored in"
" an append-only database file called *filestorage* and usually the name of "
"this file is ``Data.fs``."
msgstr "The `Plone CMS <http://plone.org>`_ from version 4.x onwards stores files and images uploaded to the `ZODB <http://www.zodb.org/>`_ as `BLOBs <http://www.zodb.org/zodbbook/introduction.html?highlight=blob#blobs>`_. They exist in a ``var/blobstorage`` folder structure on the file system, files being named after (opaque) persistent object ids. When using the default backend, the objects themselves, without file payload, are stored in an append-only database file called *filestorage* and usually the name of this file is ``Data.fs``."

# 08cf74118eb74bda9acad1c7f9ac96ab
#: ../../source/troubleshooting/transactions.rst:29
msgid ""
"If you copy the Plone site database object data (``Data.fs``) and forget to "
"copy the ``blobstorage`` folder(s), or if data gets out of the sync during "
"the copy, various problems appear on the Plone site:"
msgstr "If you copy the Plone site database object data (``Data.fs``) and forget to copy the ``blobstorage`` folder(s), or if data gets out of the sync during the copy, various problems appear on the Plone site:"

# df3ab54d66b74b73a44225b4cb5fc927
#: ../../source/troubleshooting/transactions.rst:34
msgid ""
"You cannot access a content item for which the a corresponding blob file is "
"missing from the file system;"
msgstr "You cannot access a content item for which the a corresponding blob file is missing from the file system;"

# 13160db6377b481eaa360cbd0ee0ab5d
#: ../../source/troubleshooting/transactions.rst:37
msgid "you cannot rebuild the ``portal_catalog`` indexes;"
msgstr "you cannot rebuild the ``portal_catalog`` indexes;"

# 3244e4e6ad3645f6b7f83454142542cd
#: ../../source/troubleshooting/transactions.rst:39
msgid "database packing may fail."
msgstr "database packing may fail."

# f744b44a78fb4eaabe51345e14e9a91a
#: ../../source/troubleshooting/transactions.rst:41
msgid ""
"Instead, you'll see something like this - an evil ``POSKeyError`` exception "
"(POS referring to Persistent Object Storage)::"
msgstr "Instead, you'll see something like this - an evil ``POSKeyError`` exception (POS referring to Persistent Object Storage)::"

# d13f823050594c84bd949c0f9a59e5f2
#: ../../source/troubleshooting/transactions.rst:53
msgid "The proper solution to this problem is to:"
msgstr "The proper solution to this problem is to:"

# 012162e8ab704beebeb460c21447a069
#: ../../source/troubleshooting/transactions.rst:55
msgid "Re-copy ``blobstorage`` folder;"
msgstr "Re-copy ``blobstorage`` folder;"

# 17bb8d64ef6742da9051c53169af8521
#: ../../source/troubleshooting/transactions.rst:57
msgid ""
"restart Plone twice in foreground mode (sometimes a freshly copied "
"blobstorage folder does not get picked up - some kind of timestamp issue?). "
"Restarting ZEO clients once seems to be enough."
msgstr "restart Plone twice in foreground mode (sometimes a freshly copied blobstorage folder does not get picked up - some kind of timestamp issue?). Restarting ZEO clients once seems to be enough."

# 085b2f0cbb1d4084a9596892ea1bd3a6
#: ../../source/troubleshooting/transactions.rst:62
msgid ""
"`Plone site copy instructions <http://plone.org/documentation/kb/copying-a"
"-plone-site>`_"
msgstr "`Plone site copy instructions <http://plone.org/documentation/kb/copying-a-plone-site>`_"

# 535d9f5b8ae44af78a3e751bc4040459
#: ../../source/troubleshooting/transactions.rst:64
msgid ""
"However you may have failed. You may have damaged or lost your "
"``blobstorage`` forever. To get the Plone site to a working state, all "
"content with bad BLOB data must be deleted (which usually entails losing "
"some site images and uploaded files)."
msgstr "However you may have failed. You may have damaged or lost your ``blobstorage`` forever. To get the Plone site to a working state, all content with bad BLOB data must be deleted (which usually entails losing some site images and uploaded files)."

# e4c6fdac54a440868888f78b42a077e5
#: ../../source/troubleshooting/transactions.rst:70
msgid ""
"Below is Python code for a `Grok view <http://collective-"
"docs.readthedocs.org/en/latest/views/browserviews.html#creating-a-view-"
"using-grok>`_ which you can drop in to your own `Plone add-on product <http"
"://collective-docs.readthedocs.org/en/latest/tutorials/paste.html#creating-"
"an-add-on-product-skeleton>`_. It creates an admin view which you can call "
"directly via an URL. This code will walk through all the content on your "
"Plone site and try to delete bad content items with BLOBs missing."
msgstr "Below is Python code for a `Grok view <http://collective-docs.readthedocs.org/en/latest/views/browserviews.html#creating-a-view-using-grok>`_ which you can drop in to your own `Plone add-on product <http://collective-docs.readthedocs.org/en/latest/tutorials/paste.html#creating-an-add-on-product-skeleton>`_. It creates an admin view which you can call directly via an URL. This code will walk through all the content on your Plone site and try to delete bad content items with BLOBs missing."

# 5653574cdafa4f50a1a6c5fc47955c3a
#: ../../source/troubleshooting/transactions.rst:78
msgid ""
"The code handles both Archetypes and Dexterity subsystems' content types."
msgstr "The code handles both Archetypes and Dexterity subsystems' content types."

# c1e08c585c1943258ae4973114467dce
#: ../../source/troubleshooting/transactions.rst:82
msgid ""
"Fixing Dexterity blobs with this code has never been tested - please feel "
"free to update the code in collective.developermanual on GitHub if you find "
"it not working properly."
msgstr "Fixing Dexterity blobs with this code has never been tested - please feel free to update the code in collective.developermanual on GitHub if you find it not working properly."

# c02df8aea49e45c1a2c9dae747b2ec3a
#: ../../source/troubleshooting/transactions.rst:87
msgid "The code, ``fixblobs.py``::"
msgstr "The code, ``fixblobs.py``::"

# e37c82a6b4c64a6e81e5b03339eaea35
#: ../../source/troubleshooting/transactions.rst:231
msgid ""
"http://stackoverflow.com/questions/8655675/cleaning-up-poskeyerror-no-blob-"
"file-content-from-plone-site"
msgstr "http://stackoverflow.com/questions/8655675/cleaning-up-poskeyerror-no-blob-file-content-from-plone-site"

# 78770fe30585469db17bf6700d0dcddf
#: ../../source/troubleshooting/transactions.rst:233
msgid "http://pypi.python.org/pypi/experimental.gracefulblobmissing/"
msgstr "http://pypi.python.org/pypi/experimental.gracefulblobmissing/"

# 5447a84a26454cefab21423864948784
#: ../../source/troubleshooting/transactions.rst:237
msgid "Transactions"
msgstr "Transactions"

# d4de458b0c26405d8599df0713455ab5
#: ../../source/troubleshooting/transactions.rst:239
msgid ""
"Transactions are usually problematic only when many ZEO front-end clients "
"are used."
msgstr "Transactions are usually problematic only when many ZEO front-end clients are used."

# 77dbf447eba74e49832d561a5fff6db7
#: ../../source/troubleshooting/transactions.rst:243
msgid "ConflictError"
msgstr "ConflictError"

# a56599f9e1fd40e3b0e5070c50bba0cd
#: ../../source/troubleshooting/transactions.rst:245
msgid ""
"When the site gets more load, ``ConflictError``\\s start to occur. Zope "
"tries to solve the situation by replaying HTTP requests for "
"``ConflictError``\\s and has a default threshold (3) of how many times the "
"request is replayed."
msgstr "When the site gets more load, ``ConflictError``\\s start to occur. Zope tries to solve the situation by replaying HTTP requests for ``ConflictError``\\s and has a default threshold (3) of how many times the request is replayed."

# 0b0f92408da24203804ca64375f2e297
#: ../../source/troubleshooting/transactions.rst:252
msgid "http://www.zopyx.com/blog/on-zodb-conflict-resolution"
msgstr "http://www.zopyx.com/blog/on-zodb-conflict-resolution"

# 2d9287f236d74751948d358a480b265f
#: ../../source/troubleshooting/transactions.rst:255
msgid "How to debug which object causes ``ConflictError``\\s"
msgstr "How to debug which object causes ``ConflictError``\\s"

# 35b89d9ae77f423e89d0db152fb0b4bd
#: ../../source/troubleshooting/transactions.rst:257
msgid ""
"``ConflictError``\\s are caused by concurrent transactions trying to write "
"to the same object(s) - usually ``portal_catalog``. They are harmless, but "
"slow down badly coded sites. Plone will retry the HTTP request and "
"transaction three times before giving up."
msgstr "``ConflictError``\\s are caused by concurrent transactions trying to write to the same object(s) - usually ``portal_catalog``. They are harmless, but slow down badly coded sites. Plone will retry the HTTP request and transaction three times before giving up."

# a73d24e66ba242e6bd8ad84ea2fec211
#: ../../source/troubleshooting/transactions.rst:262
msgid "The OID is visible in the ConflictError traceback."
msgstr "The OID is visible in the ConflictError traceback."

# 5e245d5c4c1a49bb81cbea2314344221
#: ../../source/troubleshooting/transactions.rst:264
msgid ""
"You can turn OID back to the corresponding Python object, as mentioned by A."
" Jung::"
msgstr "You can turn OID back to the corresponding Python object, as mentioned by A. Jung::"

# 4e458b0080994f6980c163b5b841260e
#: ../../source/troubleshooting/transactions.rst:271
msgid "If every transaction appears as write transaction"
msgstr "If every transaction appears as write transaction"

# 947d0f98113f462d81c4c63c1d55feda
#: ../../source/troubleshooting/transactions.rst:273
msgid ""
"If you are not careful, you may accidentally write code which turns all "
"transactions to write transactions. This typically happens when you call "
"some method without realizing that that method eventually modifies a "
"persistent object, causing a database write."
msgstr "If you are not careful, you may accidentally write code which turns all transactions to write transactions. This typically happens when you call some method without realizing that that method eventually modifies a persistent object, causing a database write."

# d8e009aea296410e8afa46e2c7a1f57e
#: ../../source/troubleshooting/transactions.rst:279
msgid "Symptoms:"
msgstr "Symptoms:"

# 0705e14abc04483d8440fd4cd4bb36aa
#: ../../source/troubleshooting/transactions.rst:281
msgid ""
"Your Undo tab in ZMI will be full of entries, one added per page request."
msgstr "Your Undo tab in ZMI will be full of entries, one added per page request."

# dec26db4d9cd4dc4bc40485f70ac5269
#: ../../source/troubleshooting/transactions.rst:284
msgid "If you run the server in single Zope server mode, it is slow."
msgstr "If you run the server in single Zope server mode, it is slow."

# b67f116bb78c4399a5d64ac70fa0a251
#: ../../source/troubleshooting/transactions.rst:286
msgid ""
"If you run the server in ZEO mode you get the exceptions like one below. It "
"may happen even with one user. This is because each page load requres more "
"than one HTTP request: HTML load, image load, CSS load and so on. Browser "
"makes many requests per page and those transactions are conflicting, because"
" they are all write transactions."
msgstr "If you run the server in ZEO mode you get the exceptions like one below. It may happen even with one user. This is because each page load requres more than one HTTP request: HTML load, image load, CSS load and so on. Browser makes many requests per page and those transactions are conflicting, because they are all write transactions."

# 3fd2989852194a799c9db13fe090dc53
#: ../../source/troubleshooting/transactions.rst:316
msgid "How to debug it"
msgstr "How to debug it"

# c17608d96b1b4d458471af5eb319360e
#: ../../source/troubleshooting/transactions.rst:318
msgid ""
"Zope 2 doesn't have many well-documented ZODB debugging tools. Below is one "
"snippet to examine the contents of the last transactions of an offline "
"``Data.fs`` file. It is an evolved version of `this original script "
"<http://www.mail-archive.com/zodb-dev@zope.org/msg04387.html>`_."
msgstr "Zope 2 doesn't have many well-documented ZODB debugging tools. Below is one snippet to examine the contents of the last transactions of an offline ``Data.fs`` file. It is an evolved version of `this original script <http://www.mail-archive.com/zodb-dev@zope.org/msg04387.html>`_."

# 84f97f8da79943a9b875cfc8a5e7f2e8
#: ../../source/troubleshooting/transactions.rst:324
msgid "Do something on a badly behaving site."
msgstr "Do something on a badly behaving site."

# 0602f019d5724dcd9fdaca58abb002ff
#: ../../source/troubleshooting/transactions.rst:326
msgid "Stop Zope instance."
msgstr "Stop Zope instance."

# fcdc444616d5420a87d611add4e7851b
#: ../../source/troubleshooting/transactions.rst:328
msgid ""
"Run the script below (``debug.py``) on the ``Data.fs`` file to see what "
"objects have been changed."
msgstr "Run the script below (``debug.py``) on the ``Data.fs`` file to see what objects have been changed."

# 7e942cf98eea4e56ba12a37f9f6158f6
#: ../../source/troubleshooting/transactions.rst:331
msgid "Guess the badly behaving code from the object class name."
msgstr "Guess the badly behaving code from the object class name."

# 4345810a52f849e99b5b0dd73dae70ad
#: ../../source/troubleshooting/transactions.rst:333
msgid ""
"Example how to run the script for the last 30 transaction under a Zope egg "
"environment using the ``zopepy`` script::"
msgstr "Example how to run the script for the last 30 transaction under a Zope egg environment using the ``zopepy`` script::"

# a1695ac0a69c4d3581e31c4609dc17d6
#: ../../source/troubleshooting/transactions.rst:339
msgid ""
"The following is obsolete with current Zope. FileIterator does not take a "
"``pos`` argument any more."
msgstr "The following is obsolete with current Zope. FileIterator does not take a ``pos`` argument any more."

# 9b59590807584e80a24626ba96a649a8
#: ../../source/troubleshooting/transactions.rst:342
msgid "Code for debug.py::"
msgstr "Code for debug.py::"

# bcda8ecf3a8a4416b0271f7254b35630
#: ../../source/troubleshooting/unicode.rst:3
msgid "Unicode encoding and decoding"
msgstr "Unicode encoding and decoding"

# d1d8149d73854e7b92dc7a968ad2b996
#: ../../source/troubleshooting/unicode.rst:8
msgid "Introduction: Why unicode is difficult?"
msgstr "Introduction: Why unicode is difficult?"

# 2e2483220c854a18b2aae53f478528ea
#: ../../source/troubleshooting/unicode.rst:10
msgid "Python 2.x does not make a clear distinction between:"
msgstr "Python 2.x does not make a clear distinction between:"

# f16bffebb0f64b95958cbb5d385390a2
#: ../../source/troubleshooting/unicode.rst:12
msgid "8-bit strings (byte data)"
msgstr "8-bit strings (byte data)"

# 8f0a84e45e8d44538c0e400ef602fcf4
#: ../../source/troubleshooting/unicode.rst:13
msgid "16-bit unicode strings (character data)"
msgstr "16-bit unicode strings (character data)"

# 991fe18c688741f9aef8e98b498862f9
#: ../../source/troubleshooting/unicode.rst:15
msgid ""
"Developers use these two formats interchangeably, because it is so easy and "
"Python does not warn you about this."
msgstr "Developers use these two formats interchangeably, because it is so easy and Python does not warn you about this."

# 9fa04caf1711416186c41ef602933995
#: ../../source/troubleshooting/unicode.rst:18
msgid ""
"However, it will only work as long as the input does not encounter any "
"international, non-ASCII, characters.  When 8-bit encoded string data and "
"16-bit raw Unicode string data gets mixed up, by being run through encoding "
"first, really nasty things start to happen."
msgstr "However, it will only work as long as the input does not encounter any international, non-ASCII, characters.  When 8-bit encoded string data and 16-bit raw Unicode string data gets mixed up, by being run through encoding first, really nasty things start to happen."

# 38bca4f57a064678805050c0cdd5701e
#: ../../source/troubleshooting/unicode.rst:23
msgid "Read more:"
msgstr "Read more:"

# 041934b2245f4836ad46be328cbd7275
#: ../../source/troubleshooting/unicode.rst:25
msgid "http://www.amk.ca/python/howto/unicode"
msgstr "http://www.amk.ca/python/howto/unicode"

# 199702074bdc4e8886a576ee7ab31bb3
#: ../../source/troubleshooting/unicode.rst:27
msgid "http://evanjones.ca/python-utf8.html"
msgstr "http://evanjones.ca/python-utf8.html"

# f99192babbf8469b90dd27d46082d7ef
#: ../../source/troubleshooting/unicode.rst:30
msgid "safe_unicode()"
msgstr "safe_unicode()"

# a85ff9a54c7a4026ad23c363d677c5dc
#: ../../source/troubleshooting/unicode.rst:32
msgid ""
"Plone's core contains a helper function which allows you to safely decode "
"strings to unicode without fear of UnicodeDecodeException. Use this in your "
"own code to decode unicode in the cases you are not sure if the input is "
"8-bit bytestrings or real unicode strings."
msgstr "Plone's core contains a helper function which allows you to safely decode strings to unicode without fear of UnicodeDecodeException. Use this in your own code to decode unicode in the cases you are not sure if the input is 8-bit bytestrings or real unicode strings."

# 72451a07aee2400798d23ece3374c953
#: ../../source/troubleshooting/unicode.rst:37
msgid ""
"https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/utils.py#L434"
msgstr "https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/utils.py#L434"

# b01fe3ccf7b14948a8d8ef1e481d0102
#: ../../source/troubleshooting/unicode.rst:50
msgid "sys.setdefaultencoding()"
msgstr "sys.setdefaultencoding()"

# 73e9c1eb31d94936ad5120fc744e67cc
#: ../../source/troubleshooting/unicode.rst:52
msgid ""
"Python has a **system-wide** setting to enforce encoding of all unicode "
"input automatically to utf-8 when used as 8-bit string."
msgstr "Python has a **system-wide** setting to enforce encoding of all unicode input automatically to utf-8 when used as 8-bit string."

# 8b8e9fe020334123ad953e865ac8385e
#: ../../source/troubleshooting/unicode.rst:57
msgid ""
"This is a wrong way to fix things and it will break other things. You have "
"been warned."
msgstr "This is a wrong way to fix things and it will break other things. You have been warned."

# 77d815cccb0d4a8193004c0f3cc3ee68
#: ../../source/troubleshooting/unicode.rst:60
msgid ""
"http://tarekziade.wordpress.com/2008/01/08/syssetdefaultencoding-is-evil/"
msgstr "http://tarekziade.wordpress.com/2008/01/08/syssetdefaultencoding-is-evil/"

# 3b19b86b50a9494d8b4b69fee0ea8e93
#: ../../source/troubleshooting/unicode.rst:62
msgid ""
"There is also ``sitecustomization.py`` trick to set "
"``sys.setdefaultencoding(\"utf-8\")`` on per-script basis"
msgstr "There is also ``sitecustomization.py`` trick to set ``sys.setdefaultencoding(\"utf-8\")`` on per-script basis"

# 24daf49bd5cd4d5294575eea8b5e57a2
#: ../../source/troubleshooting/unicode.rst:64
msgid "http://stackoverflow.com/a/7892892/315168"
msgstr "http://stackoverflow.com/a/7892892/315168"

# 1bb216701d1f4a808df143681c251f67
#: ../../source/troubleshooting/unicode.rst:67
msgid "UnicodeEncodeError"
msgstr "UnicodeEncodeError"

# 71a333feb72d43c58f58d7e758584747
#: ../../source/troubleshooting/unicode.rst:69
msgid ""
"``UnicodeEncodeError``: 'ascii' codec can't encode character u'\\xe4' in "
"position 4: ordinal not in range(128)"
msgstr "``UnicodeEncodeError``: 'ascii' codec can't encode character u'\\xe4' in position 4: ordinal not in range(128)"

# 716920cb354d4fb4a31554cdad20b782
#: ../../source/troubleshooting/unicode.rst:71
msgid ""
"This is usually because you are trying to output/store unicode data using "
"outdated methods, e.g."
msgstr "This is usually because you are trying to output/store unicode data using outdated methods, e.g."

# 6d8ec9ff561a46eea43a3acaed8de779
#: ../../source/troubleshooting/unicode.rst:74
msgid "printing,"
msgstr "printing,"

# 7e1612f9ac5646d79754437b1faa6078
#: ../../source/troubleshooting/unicode.rst:75
msgid "logging,"
msgstr "logging,"

# 0aa66c68e5174315ba1ef3f29354ff2a
#: ../../source/troubleshooting/unicode.rst:76
msgid "using 7-bit ids ..."
msgstr "using 7-bit ids ..."

# f7a59c0c8e944aaeb741870c61e96e32
#: ../../source/troubleshooting/unicode.rst:78
msgid "Instead of::"
msgstr "Instead of::"

# 2e35d98648c441cdbde795a3dff76f5e
#: ../../source/troubleshooting/unicode.rst:82
msgid "do::"
msgstr "do::"

# c349c143cace4a4080de4280ad471f04
#: ../../source/troubleshooting/unicode.rst:86
msgid "Filtering example::"
msgstr "Filtering example::"

# af9edb10c9eb42d980c166b5d614bb0f
#: ../../source/troubleshooting/unicode.rst:97
msgid "UnicodeDecodeError"
msgstr "UnicodeDecodeError"

# c8ad01e165954a80b5f5d7a7bd86bd9a
#: ../../source/troubleshooting/unicode.rst:99
msgid "http://wiki.python.org/moin/UnicodeDecodeError"
msgstr "http://wiki.python.org/moin/UnicodeDecodeError"

# bc9d008e54fe4de28ffb6d31691da347
#: ../../source/troubleshooting/unicode.rst:102
msgid "Safe way to ``decode()`` strings"
msgstr "Safe way to ``decode()`` strings"

# d5b4a3dec5324ed88e524b9d209de4a2
#: ../../source/troubleshooting/unicode.rst:104
msgid ""
"This example will accept all string input and convert it to proper unicode "
"strings."
msgstr "This example will accept all string input and convert it to proper unicode strings."

# 585658e42f1f4379a49fbdfda7048c04
#: ../../source/troubleshooting/unicode.rst:118
msgid "http://pyref.infogami.com/__unicode__"
msgstr "http://pyref.infogami.com/__unicode__"

# 2a6a47bc3d2d47cebb1089edc4adc462
#: ../../source/troubleshooting/unicode.rst:121
msgid "Infamous non-breaking Unicode space \\\\xa0"
msgstr "Infamous non-breaking Unicode space \\\\xa0"

# c9926b20c7c9447cb7c12096abf83353
#: ../../source/troubleshooting/unicode.rst:123
msgid "Press CTRL+space / AltGr space on Linux to accidentally create it."
msgstr "Press CTRL+space / AltGr space on Linux to accidentally create it."

# fff96e59959242f9a853a0b8daf5b6cb
#: ../../source/troubleshooting/unicode.rst:125
msgid "**You can't see it.** But it breaks everything."
msgstr "**You can't see it.** But it breaks everything."

# 612d62b6b70a414e89577417d288a776
#: ../../source/troubleshooting/unicode.rst:130
msgid ""
"Example to how to fix non-breaking space characters which have ended up in "
"reStructuredText ``.txt`` files.  This is Unicode character code A0."
msgstr "Example to how to fix non-breaking space characters which have ended up in reStructuredText ``.txt`` files.  This is Unicode character code A0."

# e7de81e550cc401cb4e7436d21208595
#: ../../source/troubleshooting/unicode.rst:133
msgid "Example fix_wtf_space.py::"
msgstr "Example fix_wtf_space.py::"
